/**
 * Populate search_terms for all business categories
 *
 * Fills the search_terms TEXT[] column with comprehensive synonyms,
 * colloquial terms, and related keywords in Chinese + English.
 *
 * Usage:
 *   source apps/web/.env.local && npx tsx scripts/populate-search-terms.ts
 */

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

async function update(slug: string, terms: string[]) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/categories?slug=eq.${slug}`, {
    method: 'PATCH',
    headers: {
      'apikey': SUPABASE_KEY,
      'Authorization': `Bearer ${SUPABASE_KEY}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=minimal',
    },
    body: JSON.stringify({ search_terms: terms }),
  });
  const status = res.ok ? '✅' : '❌';
  console.log(`  ${status} ${slug} (${terms.length} terms)`);
}

const TERMS: Record<string, string[]> = {
  // ═══ FOOD & DINING ═══
  'food-dining': [
    '餐饮', '美食', '吃饭', '餐厅', '饭店', '饭馆', '食堂', '吃什么', '好吃的', '觅食',
    '找餐厅', '附近餐厅', '推荐餐厅', '好吃的餐厅', '网红餐厅', '排队',
    '聚餐', '请客', '约饭', '团建', '朋友聚会', '家庭聚餐', '生日聚餐',
    '外卖', '打包', '堂食', '预约', '订位', '等位',
    '中文菜单', '华人餐厅', '中国人开的',
    '早餐', '午餐', '晚餐', '宵夜', '夜宵', '早午餐', 'brunch',
    '自助', '自助餐', 'buffet', '食堂',
    'restaurant', 'food', 'dining', 'eat', 'where to eat', 'best restaurant',
    'delivery', 'Uber Eats', 'DoorDash', 'Grubhub', 'takeout',
  ],
  'food-chinese': [
    '中餐', '中国菜', '中餐馆', '中餐厅', '中国餐厅', '找中餐', '好吃的中餐',
    '川菜', '四川菜', '麻辣', '水煮鱼', '回锅肉', '麻婆豆腐', '宫保鸡丁', '辣子鸡', '酸菜鱼',
    '粤菜', '广东菜', '烧腊', '烧鸭', '烧鹅', '白切鸡', '煲仔饭', '老火汤',
    '湘菜', '湖南菜', '剁椒鱼头', '小炒肉',
    '东北菜', '锅包肉', '地三鲜', '杀猪菜', '小鸡炖蘑菇', '饺子', '东北饺子',
    '上海菜', '本帮菜', '小笼包', '生煎', '红烧肉', '上海生煎',
    '北京菜', '北京烤鸭', '烤鸭', '涮羊肉',
    '鲁菜', '闽菜', '福建菜', '客家菜', '江浙菜', '淮扬菜', '云南菜', '贵州菜', '新疆菜',
    '炒菜', '家常菜', '小炒', '盖浇饭', '炒饭', '炒面',
    '烧烤', '撸串', '羊肉串', 'BBQ',
    '包子', '馒头', '煎饼', '油条', '豆浆', '早点', '中式早餐',
    'Chinese food', 'Chinese restaurant', 'Sichuan', 'Cantonese', 'Shanghainese',
    'Hunan', 'dim sum', 'dumpling', 'Peking duck', 'fried rice', 'chow mein',
  ],
  'food-japanese': [
    '日料', '日本菜', '日餐', '日本料理', '日式', '找日料', '好吃的日料',
    '寿司', '手握寿司', '寿司店', '回转寿司', '外卖寿司', 'omakase', '厨师长推荐',
    '刺身', '生鱼片', '三文鱼', '金枪鱼', '鰻魚',
    '拉面', '日式拉面', '味噌拉面', '豚骨拉面', '盐味拉面', '酱油拉面',
    '天妇罗', '炸虾', '炸物',
    '居酒屋', '烧鸟', '串烧', '日式烧烤',
    '乌冬', '乌冬面', '荞麦面', '冷面',
    '定食', '便当', '日式便当', '咖喱饭', '日式咖喱',
    '日式火锅', '涮涮锅', '寿喜烧',
    '抹茶', '日式甜品', '铜锣烧', '大福',
    'sushi', 'ramen', 'Japanese', 'Japanese restaurant', 'izakaya',
    'sashimi', 'tempura', 'udon', 'teriyaki', 'omakase', 'yakitori', 'tonkatsu',
  ],
  'food-korean': [
    '韩餐', '韩国菜', '韩式', '韩国料理', '找韩餐', '好吃的韩餐',
    '烤肉', '韩国烤肉', '韩式烤肉', '五花肉', '牛肋排', '烤肉店',
    '石锅拌饭', '拌饭', '泡菜', '韩国泡菜', '辣白菜',
    '部队锅', '泡菜锅', '大酱汤', '豆腐锅', '嫩豆腐煲',
    '炸鸡', '韩式炸鸡', '啤酒炸鸡', '芝士炸鸡',
    '冷面', '韩式冷面', '拌冷面',
    '紫菜包饭', '韩式煎饼', '辣炒年糕', '年糕',
    '韩式炸酱面', '参鸡汤', '排骨汤', '牛尾汤',
    '韩国甜品', '冰沙', '红豆冰',
    'Korean', 'Korean restaurant', 'Korean BBQ', 'BBQ', 'KBBQ',
    'bibimbap', 'kimchi', 'fried chicken', 'bulgogi', 'japchae', 'soju',
  ],
  'food-hotpot': [
    '火锅', '火锅店', '找火锅', '好吃的火锅', '火锅推荐',
    '麻辣烫', '麻辣香锅', '冒菜', '关东煮',
    '串串', '串串香', '冷锅串串',
    '涮锅', '涮羊肉', '铜锅涮肉',
    '鸳鸯锅', '九宫格', '清汤锅', '番茄锅', '菌菇锅', '骨汤锅',
    '海底捞', '自助火锅', '旋转火锅', '一人火锅',
    '毛肚', '鸭血', '肥牛', '牛肉丸', '虾滑', '豆腐', '蔬菜拼盘',
    '蘸料', '芝麻酱', '油碟',
    '重庆火锅', '四川火锅', '潮汕火锅', '椰子鸡', '酸菜鱼火锅',
    'hotpot', 'hot pot', 'shabu shabu', 'Sichuan hotpot', 'spicy pot',
    'all you can eat hotpot', 'mala tang', 'mala',
  ],
  'food-bubble-tea': [
    '奶茶', '奶茶店', '找奶茶', '好喝的奶茶', '奶茶推荐',
    '茶饮', '珍珠奶茶', '珍珠', '波霸', '波霸奶茶',
    '鲜茶', '果茶', '水果茶', '柠檬茶', '百香果', '芒果', '葡萄',
    '手摇茶', '手摇饮料', '冰沙', '奶昔',
    '芋圆', '椰果', '红豆', '仙草', '布丁', '奶盖', '芝士奶盖',
    '黑糖', '黑糖珍珠', '脏脏奶茶',
    '抹茶', '抹茶拿铁', '乌龙茶', '铁观音', '茉莉花茶',
    '贡茶', '虎糖', 'CoCo', '日出茶太', '快乐柠檬', '鲜茶道',
    'bubble tea', 'boba', 'milk tea', 'boba tea', 'fruit tea',
    'taro', 'matcha', 'brown sugar boba', 'tea shop', 'Kung Fu Tea',
  ],
  'food-bakery': [
    '面包', '面包店', '找面包店', '好吃的面包',
    '蛋糕', '蛋糕店', '生日蛋糕', '订蛋糕', '定制蛋糕', '翻糖蛋糕', '奶油蛋糕', '慕斯蛋糕', '芝士蛋糕',
    '烘焙', '甜品', '西点', '糕点', '点心',
    '吐司', '牛角包', '可颂', '法棍', '法式面包', '欧包', '全麦面包', '杂粮面包',
    '中式糕点', '月饼', '蛋黄酥', '凤梨酥', '绿豆糕', '老婆饼',
    '泡芙', '马卡龙', '千层', '提拉米苏', '派', '挞', '蛋挞',
    '饼干', '曲奇', '甜甜圈',
    '婚礼蛋糕', '满月蛋糕', '节日糕点',
    'bakery', 'cake', 'pastry', 'bread', 'birthday cake', 'custom cake',
    'croissant', 'macaron', 'dessert', 'patisserie', 'cupcake', 'donut',
  ],
  'food-dim-sum': [
    '点心', '早茶', '饮茶', '喝早茶', '叹早茶', '吃点心',
    '茶楼', '茶餐厅', '港式', '港式点心', '广式点心',
    '虾饺', '水晶虾饺', '烧卖', '干蒸烧卖',
    '肠粉', '布拉肠', '鲜虾肠粉', '叉烧肠',
    '叉烧包', '奶黄包', '流沙包', '莲蓉包',
    '萝卜糕', '芋头糕', '马蹄糕',
    '凤爪', '豉汁凤爪', '排骨', '豆豉蒸排骨',
    '蛋挞', '菠萝包', '鸡蛋仔',
    '糯米鸡', '粥', '皮蛋瘦肉粥', '艇仔粥',
    '推车', '推车点心',
    '小笼包', '小笼', '汤包', '灌汤包', '生煎', '生煎包', '锅贴',
    'dim sum', 'yum cha', 'Cantonese', 'Hong Kong style', 'tea house',
    'dumplings', 'siu mai', 'har gow', 'char siu bao', 'rice roll', 'egg tart',
    'soup dumpling', 'xiao long bao', 'pan fried bun',
  ],
  'food-noodles': [
    '面馆', '面条', '面食', '吃面', '找面馆', '好吃的面',
    '拉面', '手拉面', '兰州拉面', '兰州牛肉面',
    '牛肉面', '红烧牛肉面', '清汤牛肉面',
    '刀削面', '炸酱面', '阳春面', '葱油面', '担担面', '热干面', '重庆小面', '臊子面',
    '米粉', '桂林米粉', '螺蛳粉', '湖南米粉', '肠粉',
    '河粉', '炒河粉', '干炒牛河', '沙河粉',
    '粉丝', '酸辣粉', '红薯粉',
    '凉面', '凉皮', '冷面',
    '馄饨', '云吞', '抄手', '饺子', '水饺', '煎饺', '蒸饺', '锅贴',
    '刀削', '手擀面', '宽面', '细面',
    'noodle', 'noodle shop', 'ramen', 'hand-pulled noodle', 'dumpling',
    'wonton', 'chow fun', 'pho', 'lo mein', 'chow mein', 'rice noodle',
  ],
  'food-seafood': [
    '海鲜', '海鲜餐厅', '找海鲜', '好吃的海鲜', '海鲜推荐', '海鲜大排档',
    '鱼', '清蒸鱼', '红烧鱼', '烤鱼', '水煮鱼', '酸菜鱼', '石斑鱼', '鲈鱼',
    '虾', '大虾', '白灼虾', '盐焗虾', '椒盐虾', '虾仁',
    '蟹', '螃蟹', '大闸蟹', '帝王蟹', '花蟹', '炒蟹',
    '龙虾', '波士顿龙虾', '芝士焗龙虾', '蒜蓉龙虾',
    '生蚝', '牡蛎', '扇贝', '贝类', '蛤蜊', '花甲', '青口',
    '鱿鱼', '章鱼', '墨鱼', '鲍鱼', '海参', '海胆',
    '小龙虾', '蒜蓉小龙虾', '十三香小龙虾',
    '刺身', '海鲜拼盘', '海鲜自助',
    'seafood', 'fish', 'lobster', 'crab', 'shrimp', 'oyster', 'clam',
    'seafood restaurant', 'raw bar', 'fish market', 'crawfish', 'scallop',
  ],
  'food-vietnamese': [
    '越南菜', '越南餐厅', '越南料理', '找越南菜',
    '越南粉', '河粉', '牛肉粉', '鸡肉粉', '生牛肉粉',
    '春卷', '越南春卷', '鲜虾春卷', '炸春卷',
    '法棍', '越南法棍', '法棍三明治',
    '越南咖啡', '滴漏咖啡', '冰咖啡',
    '甘蔗虾', '越南米卷', '碎肉饭', '捞檬',
    'pho', 'Vietnamese', 'Vietnamese restaurant', 'banh mi', 'spring roll',
    'bun', 'vermicelli', 'Vietnamese coffee', 'boba',
  ],
  'food-thai': [
    '泰餐', '泰国菜', '泰式', '泰国料理', '找泰餐', '好吃的泰餐',
    '冬阴功', '冬荫功', '酸辣汤', '泰式酸辣汤',
    '绿咖喱', '红咖喱', '黄咖喱', '泰式咖喱', 'Massaman',
    '泰式炒河粉', 'Pad Thai', '炒粿条',
    '芒果糯米饭', '泰式奶茶', '泰式冰茶',
    '青木瓜沙拉', '泰式沙拉', '凉拌',
    '椰子鸡汤', '泰式烤鸡', '冬粉', '泰式火锅',
    'Thai', 'Thai restaurant', 'Thai food', 'Pad Thai', 'Tom Yum',
    'curry', 'green curry', 'Thai tea', 'papaya salad', 'basil chicken',
  ],
  'food-asian-fusion': [
    '亚洲融合', '创意菜', '混搭', '新派', '新派亚洲菜', '创意料理',
    '跨菜系', '混合风格', '新中餐', '新式中餐',
    '网红餐厅', '时尚餐厅', '约会餐厅', '情调餐厅',
    'Asian fusion', 'fusion', 'modern Asian', 'contemporary Asian',
    'fusion restaurant', 'creative cuisine',
  ],
  'food-american': [
    '美式', '美国菜', '美式餐厅', '西餐', '西餐厅', '找西餐',
    '汉堡', '芝士汉堡', '牛肉汉堡', '汉堡包', '炸鸡汉堡',
    '牛排', '牛排馆', '西冷', '菲力', '肋眼', '纽约客', 'T骨',
    '三明治', '潜艇堡', 'sub', '俱乐部三明治',
    '炸鸡', '美式炸鸡', '鸡翅', 'Buffalo wings',
    '烧烤', '美式BBQ', '猪肋排', '牛腩', '烟熏',
    '沙拉', '凯撒沙拉', '意面', '通心粉',
    '早午餐', 'brunch', '华夫饼', '煎饼', '班尼迪克蛋',
    'American', 'American restaurant', 'burger', 'steak', 'steakhouse',
    'sandwich', 'fried chicken', 'BBQ', 'wings', 'brunch', 'diner',
  ],
  'food-pizza': [
    '披萨', '比萨', '披萨店', '找披萨', '好吃的披萨',
    '纽约披萨', '薄底披萨', '意式披萨', '芝加哥深盘',
    '外卖披萨', '送披萨', '打电话叫披萨',
    '芝士', '意大利辣肠', 'Pepperoni', '夏威夷', '玛格丽特',
    'pizza', 'pizza shop', 'pizzeria', 'New York pizza', 'slice',
    'Dominos', 'Pizza Hut', 'delivery pizza', 'best pizza',
  ],
  'food-mexican': [
    '墨西哥菜', '墨西哥餐厅', '墨西哥料理', '找墨西哥菜',
    '塔可', '玉米饼', '卷饼', '墨西哥卷饼', 'burrito bowl',
    '芝士酱', '鳄梨酱', '牛油果', '莎莎酱', '辣酱',
    '墨西哥鸡肉', '牛肉塔可', '鱼塔可',
    '玉米片', '薯片', 'nachos', '墨西哥玉米',
    '玛格丽塔', 'tequila', '龙舌兰',
    'Mexican', 'Mexican restaurant', 'taco', 'tacos', 'burrito', 'quesadilla',
    'enchilada', 'guacamole', 'salsa', 'Chipotle', 'Taco Bell',
  ],
  'food-indian': [
    '印度菜', '印度餐厅', '印度料理', '找印度菜',
    '咖喱', '印度咖喱', '黄油鸡', '咖喱鸡', '咖喱羊肉', '咖喱虾',
    '飞饼', '印度飞饼', '馕', '印度馕', '烤饼',
    '坦都里', '坦都里鸡', '烤鸡', '印度烤肉', '羊肉串',
    '印度奶茶', '拉茶', 'chai', 'masala',
    '素食', '印度素食', '咖喱角', '萨摩萨',
    '酸奶', '芒果酸奶', '印度甜品',
    'Indian', 'Indian restaurant', 'Indian food', 'curry', 'tikka masala',
    'tandoori', 'naan', 'biryani', 'samosa', 'butter chicken', 'vindaloo',
  ],
  'food-dessert': [
    '甜品', '甜品店', '找甜品', '好吃的甜品', '甜品推荐',
    '冰淇淋', '甜点', '冰激凌', '雪糕', '冻酸奶', '冰棍', '手工冰淇淋',
    '芒果班戟', '杨枝甘露', '双皮奶', '姜撞奶', '豆腐花', '汤圆', '红豆沙', '绿豆沙',
    '蛋糕', '提拉米苏', '舒芙蕾', '可丽饼', '华夫饼', '铜锣烧',
    '水果捞', '鲜果', '刨冰', '绵绵冰', '雪花冰',
    '巧克力', '布朗尼', '马卡龙', '泡芙', '千层',
    '港式甜品', '台式甜品', '日式甜品', '法式甜品',
    'dessert', 'ice cream', 'frozen yogurt', 'gelato', 'cake',
    'waffle', 'crepe', 'macaron', 'chocolate', 'pastry', 'shaved ice',
  ],
  'food-fast-food': [
    '快餐', '快餐店', '外卖', '便当', '盒饭', '便当店',
    '打包', '点外卖', '叫外卖', '送餐', '送外卖',
    '汉堡', '薯条', '可乐', '套餐', '超值套餐',
    '炸鸡', '鸡块', '鸡翅', '鸡排',
    '中式快餐', '盖浇饭', '炒饭', '炒面', '拌面', '粥',
    '煎饼', '肉夹馍', '凉皮', '烧饼',
    'fast food', 'takeout', 'takeaway', 'delivery', 'to go',
    'McDonald', 'Burger King', 'Wendy', 'KFC', 'Popeyes', 'Chick-fil-A',
    'Uber Eats', 'DoorDash', 'Grubhub', 'Seamless',
  ],
  'food-grocery': [
    '超市', '杂货', '菜市场', '买菜', '生鲜', '食材', '粮油',
    '亚洲超市', '华人超市', '中国超市', '中国城超市',
    '水果', '蔬菜', '肉', '肉店', '猪肉', '牛肉', '鸡肉', '羊肉',
    '豆腐', '豆制品', '酱油', '调料', '调味料', '辣椒酱', '老干妈',
    '大米', '面粉', '杂粮', '干货', '腊肉', '香肠', '腊味',
    '速冻', '水饺', '汤圆', '方便面', '零食', '饼干', '膨化食品',
    '酒', '白酒', '啤酒', '红酒', '黄酒',
    '新鲜', '有机', '打折', '特价', '促销',
    '金门超市', '香港超市', '大中华', '中国城',
    'supermarket', 'grocery', 'grocery store', 'market', 'Asian supermarket',
    'H Mart', 'food market', 'farmer market', 'organic', 'fresh produce',
  ],
  'food-bar-nightlife': [
    '酒吧', '夜生活', '夜店', '找酒吧', '好酒吧',
    '鸡尾酒', '调酒', '特调', '酒单', '喝酒', '小酌',
    '啤酒', '精酿', '精酿啤酒', '扎啤', '生啤',
    '威士忌', '红酒', '白葡萄酒', '香槟', '清酒', '烧酒',
    'KTV', '卡拉OK', '唱歌', '包厢',
    '台球', '飞镖', '桌游', '棋牌',
    '蹦迪', 'DJ', '跳舞', '派对', '聚会',
    '下午茶', '静吧', '清吧', '露台', '天台酒吧',
    'bar', 'nightlife', 'pub', 'cocktail', 'club', 'nightclub',
    'lounge', 'happy hour', 'sports bar', 'wine bar', 'karaoke', 'KTV',
    'craft beer', 'brewery', 'whiskey', 'speakeasy',
  ],
  'food-catering': [
    '宴会', '外烩', '酒席', '包办酒席', '团餐', '订餐',
    '婚宴', '寿宴', '满月酒', '百日宴', '生日宴',
    '公司聚餐', '团建餐', '年会', '庆典',
    '上门做饭', '私人厨师', '家宴', '到家做菜',
    '大盆菜', '围餐', '流水席', '自助餐',
    '一桌多少钱', '几桌起订', '最低消费',
    'catering', 'banquet', 'event catering', 'party food',
    'wedding catering', 'corporate catering', 'private chef', 'buffet catering',
  ],
  'food-coffee': [
    '咖啡', '咖啡厅', '咖啡馆', '咖啡店', '找咖啡', '好喝的咖啡',
    '拿铁', '美式咖啡', '卡布奇诺', '摩卡', '浓缩', 'espresso',
    '冰咖啡', '冷萃', '手冲', '手冲咖啡', '单品咖啡', '精品咖啡',
    '燕麦拿铁', '椰奶拿铁', '植物奶',
    '自习', '工作', '学习', '安静', '有WiFi', '插座',
    '甜品', '蛋糕', '面包', '轻食', '三明治',
    '星巴克', 'Starbucks', '瑞幸',
    'coffee', 'cafe', 'coffee shop', 'latte', 'cappuccino', 'mocha',
    'cold brew', 'pour over', 'specialty coffee', 'cozy cafe', 'work cafe',
  ],

  // ═══ MEDICAL ═══
  'medical-health': [
    '医疗', '健康', '看病', '看医生', '诊所', '医院', '门诊', '找医生', '好医生', '医生推荐', '医师',
    '专科', '专科医生', '华人医生', '中文医生', '说中文的医生', '医生排名', '医生排名榜',
    '体检', '年度体检', '健康检查', '保险', '接受保险', '白卡', '红蓝卡', 'Medicaid', 'Medicare',
    'medical', 'health', 'doctor', 'clinic', 'hospital', 'Chinese doctor', 'Chinese speaking doctor',
  ],
  'medical-chinese-medicine': [
    '中医', '中医师', '中医生', '中医诊所', '老中医', '看中医', '找中医', '中医推荐', '中医排名', '中医排名榜',
    '针灸', '针灸师', '针灸诊所', '扎针', '扎针灸', '电针', '耳针', '头针',
    '推拿', '推拿师', '推拿按摩', '正骨推拿',
    '拔罐', '火罐', '放血拔罐', '走罐', '刮痧', '艾灸', '艾灸馆', '温灸', '热灸',
    '中药', '草药', '中药房', '抓药', '配药', '煎药', '汤药', '中成药', '药材',
    '经络', '穴位', '按穴位', '疏通经络',
    '中医调理', '中医养生', '中医理疗', '中医内科', '中医骨伤', '中医妇科', '中医儿科',
    '跌打损伤', '腰腿痛', '肩颈痛', '落枕', '风湿',
    'acupuncture', 'acupuncturist', 'TCM', 'Chinese medicine', 'herbal medicine', 'herbal',
    'cupping', 'moxibustion', 'tui na', 'gua sha', 'Chinese herbalist',
  ],
  'medical-dental': [
    '牙科', '牙医', '牙齿', '看牙', '洗牙', '补牙', '拔牙', '种植牙', '植牙',
    '矫正', '正畸', '牙套', '隐适美', 'Invisalign', '牙齿矫正', '整牙',
    '智齿', '拔智齿', '长智齿',
    '根管', '根管治疗', '杀神经',
    '口腔', '口腔科', '口腔医生', '口腔诊所',
    '牙周', '牙周病', '牙周炎', '牙龈出血', '牙龈肿',
    '牙科医生', '牙科诊所', '找牙医', '好牙医', '牙医推荐', '牙医排名',
    '牙冠', '牙桥', '假牙', '烤瓷牙', '全瓷牙', '贴面', '美白牙齿', '冷光美白',
    '儿童牙医', '小孩看牙', '牙科急诊', '牙疼', '牙痛', '蛀牙', '龋齿',
    'dental', 'dentist', 'teeth', 'orthodontist', 'dental clinic', 'oral surgeon',
    'teeth cleaning', 'root canal', 'dental implant', 'crown', 'bridge', 'denture',
    'teeth whitening', 'braces', 'pediatric dentist', 'emergency dental',
  ],
  'medical-optometry': [
    '眼科', '配镜', '验光', '眼镜', '眼镜店', '隐形眼镜', '美瞳',
    '近视', '远视', '散光', '老花', '老花眼', '视力', '视力检查', '眼睛',
    '眼科医生', '眼科诊所', '找眼科', '眼科推荐', '眼科排名',
    '白内障', '青光眼', '飞蚊症', '干眼症', '红眼病', '结膜炎',
    '激光手术', 'LASIK', '近视手术', '近视矫正',
    '太阳镜', '墨镜', '镜框', '镜片', '防蓝光',
    '儿童视力', '小孩近视', '弱视', '斜视',
    'optometry', 'optometrist', 'eye doctor', 'ophthalmologist', 'glasses', 'contact lens',
    'eye exam', 'vision', 'eye clinic', 'LASIK', 'cataract', 'glaucoma',
  ],
  'medical-pediatrics': [
    '儿科', '儿童', '小儿', '宝宝', '婴儿', '新生儿', '小孩',
    '儿童医生', '儿科医生', '儿科诊所', '找儿科', '儿科推荐', '儿科排名',
    '小孩看病', '宝宝看病', '带孩子看医生',
    '打疫苗', '疫苗', '预防针', '儿童疫苗', '接种',
    '发烧', '感冒', '咳嗽', '拉肚子', '腹泻', '湿疹', '过敏', '哮喘',
    '生长发育', '身高体重', '儿童体检', '入学体检',
    '母乳', '辅食', '断奶', '儿童营养',
    'pediatrics', 'pediatrician', 'children', 'kids doctor', 'child doctor',
    'baby doctor', 'newborn', 'vaccination', 'immunization', 'well-child visit',
  ],
  'medical-internal': [
    '内科', '内科医生', '内科诊所', '找内科', '内科推荐',
    '体检', '常规检查', '年度体检', '入职体检',
    '高血压', '糖尿病', '高血脂', '胆固醇', '三高',
    '胃病', '胃痛', '胃炎', '消化不良', '便秘', '胃肠', '肠胃',
    '感冒', '发烧', '咳嗽', '头痛', '头晕', '失眠',
    '甲状腺', '肝脏', '肾脏', '肺',
    '验血', '血常规', '尿检', '化验',
    'internal medicine', 'internist', 'general medicine', 'physical exam',
    'diabetes', 'hypertension', 'cholesterol', 'blood test', 'checkup',
  ],
  'medical-primary-care': [
    '家庭医生', '全科', '家医', '全科医生', '家庭医师',
    '找家庭医生', '好家庭医生', '家庭医生推荐', '家庭医生排名',
    '年检', '体检', '普通门诊', '看病', '常规检查', '年度体检',
    '开药', '处方', '转诊', '转介', 'referral',
    '打疫苗', '流感疫苗', '疫苗接种',
    '慢性病', '高血压', '糖尿病', '高血脂', '管理慢性病',
    '入职体检', '学生体检', '移民体检', 'I-693',
    'primary care', 'PCP', 'family doctor', 'family medicine', 'family physician',
    'GP', 'general practitioner', 'physical exam', 'annual checkup', 'wellness visit',
  ],
  'medical-mental-health': [
    '心理', '心理健康', '心理咨询', '心理治疗', '心理辅导',
    '心理医生', '心理咨询师', '心理治疗师', '找心理医生', '心理医生推荐',
    '精神科', '精神科医生', '精神健康',
    '抑郁', '抑郁症', '焦虑', '焦虑症', '压力', '压力大', '紧张',
    '失眠', '睡不着', '睡眠障碍', '入睡困难',
    '情绪', '情绪低落', '心情不好', '烦躁', '易怒',
    '恐慌', '强迫症', 'OCD', '创伤', 'PTSD', '躁郁', '双相',
    '自闭症', '多动症', 'ADHD', '注意力', '儿童心理',
    '婚姻咨询', '家庭咨询', '夫妻咨询', '亲子关系',
    '戒瘾', '酗酒', '药物依赖', '成瘾',
    '中文心理咨询', '华人心理医生', '说中文的心理医生',
    'mental health', 'therapy', 'therapist', 'counseling', 'counselor',
    'depression', 'anxiety', 'psychiatrist', 'psychologist', 'psychotherapy',
    'PTSD', 'OCD', 'ADHD', 'insomnia', 'stress', 'marriage counseling',
    'couples therapy', 'family therapy', 'addiction',
  ],
  'medical-obgyn': [
    '妇产科', '妇科', '产科', '妇产科医生', '妇科医生', '产科医生',
    '找妇科', '妇科推荐', '妇产科推荐', '好妇科医生',
    '怀孕', '产检', '产前检查', '孕检', '孕期', '孕妇', '备孕', '助孕',
    '生孩子', '分娩', '顺产', '剖腹产', '剖宫产', '无痛分娩',
    '月经', '月经不调', '痛经', '经期', '闭经', '更年期',
    '妇科检查', '宫颈检查', 'HPV', '宫颈癌筛查', 'Pap', '巴氏涂片',
    '子宫', '卵巢', '子宫肌瘤', '卵巢囊肿', '多囊',
    '避孕', '节育', 'IUD', '上环', '取环',
    '不孕', '不孕不育', '试管', '试管婴儿', 'IVF', '人工授精',
    '乳腺', '乳腺检查', '乳房', '钼靶',
    '产后', '产后恢复', '月子', '坐月子', '产后抑郁',
    'OB/GYN', 'OBGYN', 'gynecologist', 'obstetrician', 'pregnancy', 'prenatal',
    'fertility', 'IVF', 'maternity', 'postpartum', 'birth', 'delivery',
    'pap smear', 'mammogram', 'contraception', 'menopause',
  ],
  'medical-dermatology': [
    '皮肤科', '皮肤', '皮肤科医生', '皮肤医生', '找皮肤科', '皮肤科推荐',
    '痘痘', '青春痘', '痤疮', '粉刺', '闭口', '祛痘',
    '湿疹', '皮炎', '过敏', '皮肤过敏', '荨麻疹', '药疹',
    '脱发', '掉头发', '秃头', '斑秃', '头发稀疏', '生发',
    '皮肤癌', '黑色素瘤', '皮肤筛查', '痣', '皮肤活检',
    '牛皮癣', '银屑病', '白癜风', '色素沉着', '色斑',
    '疣', '扁平疣', '病毒疣', '鸡眼', '灰指甲', '脚气', '真菌',
    '皮肤干燥', '瘙痒', '起疹子', '红疹', '皮疹',
    '疤痕', '祛疤', '激光', '光子嫩肤', '冷冻治疗',
    'dermatology', 'dermatologist', 'skin doctor', 'skin', 'acne', 'eczema',
    'psoriasis', 'rash', 'hair loss', 'mole', 'skin cancer screening',
    'wart', 'hives', 'dermatitis', 'fungal', 'laser treatment',
  ],
  'medical-orthopedic': [
    '骨科', '骨科医生', '找骨科', '骨科推荐', '骨科排名',
    '骨头', '关节', '关节炎', '关节痛', '关节置换',
    '脊椎', '颈椎', '颈椎病', '腰椎', '椎间盘', '椎间盘突出', '腰椎间盘',
    '腰痛', '腰疼', '腰酸', '背痛', '后背疼',
    '膝盖', '膝盖痛', '膝关节', '半月板', '韧带',
    '骨折', '扭伤', '崴脚', '骨裂',
    '肩膀', '肩周炎', '五十肩', '冻结肩', '肩膀痛',
    '手腕', '腱鞘炎', '网球肘', '鼠标手', '腕管综合征',
    '骨质疏松', '缺钙', '骨密度',
    '运动损伤', '运动伤', '拉伤', '扭伤',
    '足踝', '脚痛', '足底筋膜炎', '扁平足',
    'orthopedic', 'orthopedist', 'bone doctor', 'bone', 'joint', 'spine',
    'back pain', 'knee', 'shoulder', 'fracture', 'arthritis', 'sports injury',
    'herniated disc', 'joint replacement', 'osteoporosis', 'ankle',
  ],
  'medical-physical-therapy': [
    '物理治疗', '理疗', '物理治疗师', '理疗师', '找理疗', '理疗推荐',
    '康复', '复健', '康复训练', '康复治疗', '康复中心',
    '运动伤', '运动损伤', '运动康复', '术后康复', '术后恢复',
    '腰痛', '背痛', '颈椎', '肩颈', '关节', '膝盖',
    '拉伸', '牵引', '热敷', '冷敷', '超声波', '电疗',
    '中风康复', '偏瘫', '平衡训练', '步态训练',
    '职业治疗', 'OT', '手部康复',
    '老年康复', '摔倒预防', '跌倒',
    'physical therapy', 'PT', 'physical therapist', 'rehab', 'rehabilitation',
    'sports rehab', 'occupational therapy', 'OT', 'recovery',
    'back pain', 'neck pain', 'post-surgery rehab', 'stroke rehab',
  ],
  'medical-pharmacy': [
    '药房', '药店', '买药', '处方药', '配药', '药剂师', '取药',
    '找药房', '附近药房', '华人药房', '中国人药房',
    '开药', '处方', '续处方', '补充处方',
    '非处方药', 'OTC', '感冒药', '退烧药', '止痛药', '维生素', '保健品',
    '中药房', '中药店', '抓中药', '配中药',
    '送药', '药房送药', '药品配送',
    '疫苗', '打疫苗', '流感疫苗', '新冠疫苗',
    '血压计', '血糖仪', '医疗器械', '医疗用品',
    '保险', '白卡', '红蓝卡', '药费', '处方保险',
    'pharmacy', 'pharmacist', 'drugstore', 'medicine', 'prescription',
    'CVS', 'Walgreens', 'Rite Aid', 'OTC', 'medication', 'refill',
    'Chinese pharmacy', 'herbal pharmacy', 'vaccine',
  ],
  'medical-urgent-care': [
    '急诊', '急诊室', '急救', '紧急', '急诊医生',
    '急诊诊所', '紧急护理', '即时诊所', '免预约', '免预约诊所',
    '发烧', '受伤', '伤口', '流血', '扭伤', '骨折', '烫伤', '摔伤',
    '食物中毒', '过敏反应', '呼吸困难',
    '周末看病', '晚上看病', '假日看病', '不用预约',
    '儿童急诊', '小孩急诊',
    'X光', '缝针', '包扎', '打石膏',
    'urgent care', 'ER', 'emergency', 'emergency room', 'walk-in clinic',
    'walk-in', 'no appointment', 'after hours', 'weekend clinic',
    'immediate care', 'MinuteClinic', 'CityMD',
  ],
  'medical-chiropractic': [
    '脊椎治疗', '整脊', '正骨', '整脊师', '正骨师', '找整脊', '整脊推荐',
    '脊椎', '脊柱', '脊柱侧弯', '脊椎矫正', '脊椎调整',
    '腰痛', '背痛', '颈椎', '颈椎病', '落枕', '肩颈痛', '腰椎',
    '坐骨神经', '坐骨神经痛', '椎间盘', '椎间盘突出',
    '姿势矫正', '体态', '驼背', '圆肩',
    '车祸后', '工伤', '运动伤',
    'chiropractic', 'chiropractor', 'spine', 'spinal adjustment', 'back pain',
    'neck pain', 'sciatica', 'posture', 'alignment', 'spinal correction',
  ],
  'medical-cardiology': [
    '心脏科', '心脏', '心血管', '心脏科医生', '心脏专科', '找心脏科', '心脏科推荐',
    '血压', '高血压', '低血压', '量血压',
    '心电图', 'EKG', 'ECG', '心脏彩超', '超声心动',
    '心脏病', '冠心病', '心绞痛', '心律不齐', '心律失常', '房颤', '心悸', '心慌',
    '胸闷', '胸痛', '气短', '心跳快', '心跳慢',
    '动脉硬化', '血管堵塞', '支架', '搭桥',
    '心衰', '心力衰竭',
    '胆固醇', '高血脂', '甘油三酯',
    '心脏检查', '心脏筛查', '心脏体检',
    'cardiology', 'cardiologist', 'heart doctor', 'heart', 'cardiovascular',
    'blood pressure', 'hypertension', 'EKG', 'ECG', 'echocardiogram',
    'heart disease', 'arrhythmia', 'cholesterol', 'chest pain', 'stent',
  ],
  'medical-ent': [
    '耳鼻喉', '耳鼻喉科', '耳鼻喉医生', '找耳鼻喉', '耳鼻喉推荐',
    '耳朵', '耳朵痛', '耳朵发炎', '中耳炎', '外耳炎', '耳鸣', '耳聋',
    '听力', '听力下降', '听力检查', '助听器', '耳垢', '耳屎',
    '鼻子', '鼻炎', '过敏性鼻炎', '鼻窦炎', '鼻塞', '流鼻涕', '打喷嚏', '鼻息肉',
    '喉咙', '喉咙痛', '嗓子', '嗓子疼', '声音嘶哑', '咽炎', '扁桃体', '扁桃体炎',
    '打呼噜', '打鼾', '睡眠呼吸', '睡眠呼吸暂停', '呼吸暂停',
    '鼻中隔', '鼻中隔偏曲',
    '头晕', '眩晕', '晕眩',
    'ENT', 'ear nose throat', 'otolaryngologist', 'ear doctor',
    'hearing', 'hearing loss', 'hearing aid', 'sinus', 'sinusitis',
    'sore throat', 'tonsil', 'snoring', 'sleep apnea', 'allergy', 'nasal',
    'tinnitus', 'vertigo', 'ear infection',
  ],
  'medical-allergy': [
    '过敏', '过敏科', '过敏医生', '过敏科医生', '找过敏科', '过敏科推荐',
    '花粉过敏', '花粉症', '季节性过敏', '春季过敏', '秋季过敏',
    '食物过敏', '花生过敏', '海鲜过敏', '牛奶过敏', '鸡蛋过敏', '坚果过敏',
    '药物过敏', '青霉素过敏',
    '哮喘', '气喘', '喘不过气', '呼吸困难', '支气管炎',
    '荨麻疹', '风疹块', '起疹子', '皮肤过敏', '瘙痒',
    '过敏测试', '过敏原检测', '皮肤点刺', '验血查过敏',
    '脱敏', '脱敏治疗', '过敏针', '免疫治疗',
    '尘螨', '灰尘过敏', '动物过敏', '猫过敏', '狗过敏', '霉菌过敏',
    '鼻炎', '过敏性鼻炎', '眼睛痒', '打喷嚏', '流鼻涕',
    '湿疹', '特应性皮炎',
    'allergy', 'allergist', 'asthma', 'allergic', 'allergy doctor',
    'food allergy', 'pollen', 'hay fever', 'hives', 'eczema',
    'allergy test', 'allergy shot', 'immunotherapy', 'anaphylaxis', 'EpiPen',
    'dust mite', 'pet allergy', 'seasonal allergy', 'sinus',
  ],

  // ═══ LEGAL ═══
  'legal-immigration': [
    '法律', '律师', '律师楼', '律师事务所', '法律咨询', '找律师', '好律师', '律师推荐', '律师排名',
    '诉讼', '打官司', '上法庭', '法院', '开庭', '出庭',
    '华人律师', '中文律师', '说中文的律师', '免费咨询',
    '法律援助', '法律帮助', '法律服务', '法律顾问',
    '案件', '起诉', '被告', '原告', '和解', '判决', '上诉',
    'legal', 'lawyer', 'attorney', 'law firm', 'legal service',
    'Chinese lawyer', 'Chinese speaking lawyer', 'free consultation', 'litigation',
  ],
  'legal-immigration-visa': [
    '移民', '移民律师', '找移民律师', '移民推荐', '移民咨询',
    '签证', '签证申请', '签证续签', '签证过期', '拒签',
    '绿卡', '申请绿卡', '绿卡排期', '排期', '绿卡面谈', '绿卡延期',
    '工卡', '工作许可', 'EAD', '工作签证',
    '身份', '身份问题', '黑户', '没有身份', '转身份', '调整身份',
    'H1B', 'H1B签证', 'H1B抽签', 'H4', 'L1', 'L2', 'O1', 'E2', 'B1', 'B2', 'F1', 'OPT', 'CPT',
    'EB1', 'EB2', 'EB3', 'EB5', '投资移民', '杰出人才', 'NIW', '国家利益豁免',
    '入籍', '公民', '考公民', '公民考试', '公民申请', '归化', 'N-400',
    '庇护', '政治庇护', '难民', 'asylum',
    '亲属移民', '配偶移民', '结婚绿卡', '团聚', '担保', 'I-130', 'I-485', 'I-140',
    '递解', '驱逐', '移民法庭', '递解令', '遣返',
    'DACA', '梦想者', '童年入境',
    'immigration', 'immigration lawyer', 'visa', 'green card', 'citizenship',
    'H1B', 'work permit', 'asylum', 'deportation', 'naturalization',
    'family petition', 'I-485', 'adjustment of status', 'immigration court',
  ],
  'legal-business-law': [
    '商业法', '公司法', '商业律师', '公司律师', '企业法律',
    '合同', '合同纠纷', '合同审查', '拟合同', '起草合同',
    '注册公司', '开公司', '成立公司', 'LLC', 'Inc', 'Corp', '公司注册',
    '商标', '商标注册', '商标申请', '品牌保护', '知识产权', '版权', '专利',
    '合伙', '合伙人', '股权', '股份', '合伙协议',
    '商业纠纷', '合同违约', '债务纠纷', '追讨欠款',
    '收购', '并购', '买卖生意', '转让', '店铺转让',
    '商业许可', '营业执照', '牌照', 'license',
    'business law', 'corporate law', 'contract', 'LLC', 'incorporation',
    'trademark', 'intellectual property', 'patent', 'copyright', 'partnership',
    'business dispute', 'commercial litigation',
  ],
  'legal-family': [
    '家庭法', '家庭律师', '婚姻法', '找家庭律师',
    '离婚', '离婚律师', '协议离婚', '诉讼离婚', '分居', '离婚协议',
    '监护权', '抚养权', '子女抚养', '孩子归谁', '探视权', '共同监护',
    '抚养费', '赡养费', '子女抚养费', '生活费',
    '家暴', '家庭暴力', '保护令', '限制令', '禁止令', 'order of protection',
    '婚前协议', '财产分割', '共同财产', '房产分割',
    '收养', '领养', '领养孩子', '国际收养',
    'family law', 'family lawyer', 'divorce', 'divorce lawyer', 'custody',
    'child support', 'alimony', 'domestic violence', 'prenup', 'adoption',
    'visitation', 'separation', 'marital property',
  ],
  'legal-real-estate': [
    '房产法', '房产律师', '房产纠纷', '找房产律师',
    '买房法律', '买房律师', '卖房律师', '房屋过户', '过户律师',
    '租房纠纷', '租客权益', '房东纠纷', '被房东赶', '不退押金', '押金纠纷',
    '租约', '租赁合同', '签租约', '违约', '提前退租', '驱逐',
    '产权', '产权调查', '产权保险', 'title search',
    '地契', '地税', '房产税', '税务减免',
    '合作公寓', 'co-op', 'condo', '公寓', '买公寓', '楼盘',
    'real estate law', 'real estate lawyer', 'real estate attorney',
    'closing', 'title', 'deed', 'eviction', 'tenant rights', 'landlord dispute',
    'property tax', 'lease agreement', 'housing court',
  ],
  'legal-personal-injury': [
    '人身伤害', '人身伤害律师', '找伤害律师', '索赔律师',
    '车祸', '车祸律师', '交通事故', '出车祸', '撞车', '被撞',
    '工伤', '工伤赔偿', '工地受伤', '工作受伤', '工伤保险',
    '索赔', '赔偿', '赔偿金', '保险理赔', '保险索赔',
    '摔倒', '滑倒', '绊倒', '跌倒受伤', '地面湿滑',
    '医疗事故', '医疗纠纷', '误诊', '手术失误',
    '产品责任', '缺陷产品', '食物中毒',
    '免费', '不赢不收费', '风险代理', 'no win no fee',
    'personal injury', 'injury lawyer', 'accident', 'car accident',
    'slip and fall', 'workers compensation', 'medical malpractice',
    'wrongful death', 'insurance claim', 'settlement', 'compensation',
  ],
  'legal-criminal': [
    '刑事', '刑事律师', '刑事辩护', '找刑事律师', '辩护律师',
    '犯罪', '逮捕', '被抓', '被拘留', '拘留', '坐牢',
    '保释', '保释金', 'bail', '交保释',
    '指控', '起诉', '罪名', '无罪辩护', '认罪', '减刑',
    '酒驾', 'DUI', 'DWI', '醉驾', '超速', '交通违规',
    '偷窃', '盗窃', '入室盗窃', '抢劫', '欺诈', '诈骗',
    '毒品', '持有毒品', '贩毒',
    '家暴', '袭击', '伤人', '斗殴',
    '案底', '犯罪记录', '消除案底', '封存记录',
    'criminal', 'criminal lawyer', 'criminal defense', 'defense attorney',
    'arrest', 'bail', 'DUI', 'DWI', 'felony', 'misdemeanor',
    'theft', 'assault', 'drug charge', 'expungement',
  ],
  'legal-labor': [
    '劳工法', '劳动法', '劳工律师', '劳动律师', '找劳工律师',
    '欠薪', '欠工资', '拖欠工资', '老板不给钱', '讨薪', '追讨工资', '工资纠纷',
    '工资', '最低工资', '加班费', '加班', '没给加班费', '小费', '克扣工资',
    '解雇', '被炒', '被开除', '裁员', '不当解雇', '非法解雇', '赔偿',
    '歧视', '职场歧视', '种族歧视', '性别歧视', '年龄歧视', '怀孕歧视',
    '骚扰', '性骚扰', '职场骚扰', '霸凌',
    '工伤', '工作受伤', '工伤赔偿', 'workers comp',
    '合同', '劳动合同', '保密协议', '竞业禁止', '非竞争条款',
    '报复', '举报', '吹哨人',
    'labor law', 'employment law', 'labor lawyer', 'employment lawyer',
    'unpaid wages', 'overtime', 'wrongful termination', 'discrimination',
    'harassment', 'sexual harassment', 'workers compensation', 'minimum wage',
    'retaliation', 'whistleblower', 'EEOC',
  ],
  'legal-estate-planning': [
    '遗产', '遗产规划', '遗产律师', '找遗产律师',
    '遗嘱', '立遗嘱', '写遗嘱', '修改遗嘱', '遗嘱认证', 'probate',
    '信托', '生前信托', '设立信托', '信托律师', '家族信托', '不可撤销信托',
    '继承', '继承权', '遗产继承', '财产继承', '谁来继承',
    '委托书', '授权书', '医疗授权书', '财务授权书', 'power of attorney', 'POA',
    '预先指示', '医疗指示', '生前遗嘱', '临终关怀',
    '财富传承', '资产保护', '避税', '遗产税', '赠与税',
    'estate planning', 'estate lawyer', 'will', 'trust', 'living trust',
    'probate', 'inheritance', 'power of attorney', 'estate tax',
    'asset protection', 'irrevocable trust', 'revocable trust',
  ],
  'legal-notary': [
    '公证', '公证员', '公证处', '找公证', '公证服务', '公证费',
    '翻译', '文件翻译', '翻译公证', '翻译认证', '证件翻译',
    '认证', '文件认证', '使馆认证', '领事认证', '海牙认证', 'apostille',
    '公证翻译', '翻译公司', '中英翻译', '英中翻译',
    '出生证', '出生证明翻译', '结婚证', '结婚证翻译', '学历', '学历翻译', '成绩单',
    '驾照翻译', '护照翻译', '身份证翻译',
    '宣誓', '宣誓书', '声明书', '授权书', '委托书',
    '签名见证', '签字见证', '文件签署',
    'notary', 'notary public', 'notarize', 'translation', 'certified translation',
    'apostille', 'document translation', 'Chinese translation', 'interpreter',
    'birth certificate', 'marriage certificate', 'diploma translation',
  ],

  // ═══ FINANCE ═══
  'finance-tax': [
    '财税', '税务', '财务', '财税服务', '找会计', '找税务',
    '报税', '退税', '交税', '税', '税收', '税单',
    '会计', '财务顾问', '税务顾问', '华人会计', '中文会计',
    'finance', 'tax', 'financial service', 'tax service', 'Chinese accountant',
  ],
  'finance-accounting': [
    '会计', '会计师', '注册会计师', 'CPA', '找会计', '好会计', '会计推荐', '会计排名',
    '记账', '做账', '审计', '财报', '财务报表', '月报', '年报',
    '公司会计', '企业会计', '小企业会计', '个人会计',
    '华人会计', '中文会计师', '说中文的会计',
    '税务规划', '税务筹划', '节税', '避税',
    '成本核算', '利润分析', '现金流',
    'accounting', 'accountant', 'CPA', 'certified public accountant',
    'bookkeeping', 'auditing', 'financial statement', 'tax planning',
    'Chinese accountant', 'small business accounting',
  ],
  'finance-tax-prep': [
    '报税', '退税', '报税师', '报税员', '找报税', '报税推荐',
    '个税', '个人报税', '个人所得税', '公司报税', '企业报税', '小企业报税',
    '州税', '纽约州税', '联邦税', '市税', '纽约市税',
    'W2', '1099', '1040', 'W-2', 'Schedule C', 'Schedule K-1',
    '自雇', '自雇报税', '自由职业', 'freelancer', '1099报税',
    '退税多少', '多久退税', '退税支票', '直接存款',
    '延期报税', '报税截止', '4月15', '报税季',
    '被审计', 'IRS审计', '税务问题', '欠税', '补税', '罚款',
    '抵扣', '减免', '抵税', '子女减免', '教育减免', '房贷利息', '慈善捐款',
    'ITIN', '税号', '报税号', '没有SSN怎么报税',
    'tax return', 'tax preparation', 'tax filing', 'IRS', 'tax refund',
    'income tax', 'state tax', 'federal tax', 'tax deduction', 'tax credit',
    'ITIN', 'self-employed tax', 'extension', 'amended return',
  ],
  'finance-insurance': [
    '保险', '保险经纪', '保险代理', '找保险', '买保险', '保险推荐',
    '医疗保险', '健康保险', '白卡', 'Medicaid', '红蓝卡', 'Medicare', 'Obamacare', 'ACA',
    '车险', '汽车保险', '车祸保险', '全保', '半保', '第三方',
    '房屋保险', '房屋保险', '租房保险', '租客保险', '房东保险',
    '人寿保险', '寿险', '定期寿险', '终身寿险', '储蓄型', '投资型',
    '商业保险', '店铺保险', '责任保险', '职业保险', '工伤保险', 'workers comp',
    '牙科保险', '视力保险', '眼科保险',
    '理赔', '保险理赔', '报保险', '索赔',
    '保费', '保费多少', '月费', '年费', '免赔额', 'deductible', 'copay',
    'insurance', 'health insurance', 'auto insurance', 'home insurance',
    'life insurance', 'business insurance', 'renters insurance',
    'Medicaid', 'Medicare', 'insurance broker', 'insurance agent', 'premium',
  ],
  'finance-mortgage': [
    '贷款', '房贷', '按揭', '找贷款', '贷款推荐', '贷款经纪',
    '买房贷款', '房屋贷款', '申请贷款', '贷款资格', '贷款审批',
    '再融资', 'refinance', '转贷', '重新贷款', '降利率',
    '首付', '首付比例', '首付多少', '低首付', '零首付',
    '利率', '固定利率', '浮动利率', '利率多少', '锁定利率',
    '月供', '还贷', '每月还款', '还款计划', '提前还款',
    '信用分', '信用评分', '信用不好', '低信用', '提高信用',
    '预批', '预批信', 'pre-approval', '资格审核',
    '商业贷款', '生意贷款', 'SBA贷款', 'SBA', '小企业贷款',
    '学生贷款', '车贷', '个人贷款',
    'mortgage', 'mortgage broker', 'loan', 'home loan', 'refinance',
    'down payment', 'interest rate', 'pre-approval', 'FHA', 'conventional',
    'credit score', 'monthly payment', 'closing cost',
  ],
  'finance-investment': [
    '投资', '理财', '投资顾问', '理财顾问', '找理财', '投资推荐',
    '股票', '炒股', '美股', '港股', 'A股', '股票开户', '证券',
    '基金', '共同基金', '指数基金', 'ETF', '定投',
    '退休金', '退休规划', '退休计划', '养老', '退休', '提前退休',
    '401K', '401K匹配', 'IRA', 'Roth IRA', '传统IRA', 'SEP IRA',
    '债券', '国债', '定期存款', 'CD',
    '房产投资', '出租', '投资房', '租金收入', 'rental income',
    '保险理财', '年金', '储蓄险',
    '遗产规划', '财富传承', '资产配置', '分散投资',
    '加密货币', '比特币', '数字货币', 'crypto', 'Bitcoin',
    '教育基金', '529计划', '大学储蓄',
    'investment', 'financial advisor', 'wealth management', 'stock', 'bond',
    '401K', 'IRA', 'Roth IRA', 'retirement planning', 'portfolio',
    'mutual fund', 'ETF', 'real estate investment', 'financial planning',
  ],
  'finance-bookkeeping': [
    '记账', '簿记', '对账', '做账', '财务记录',
    '代记账', '外包记账', '记账公司', '找记账',
    '流水', '收支', '收支记录', '银行对账', '对账单',
    '发票', '开发票', '收据', '报销',
    '小企业记账', '餐馆记账', '店铺记账',
    'QuickBooks', 'Xero', '记账软件',
    'bookkeeping', 'bookkeeper', 'books', 'financial records',
    'bank reconciliation', 'invoice', 'accounts receivable', 'accounts payable',
  ],
  'finance-payroll': [
    '薪资', '工资单', '发工资', '工资', '薪水',
    '薪资服务', '代发工资', '工资代发', '找薪资服务',
    '报税扣缴', '预扣税', '社保', '失业保险', '工伤保险',
    '员工福利', '加班费', '奖金', '提成',
    'W-2', '1099', '工资条', '工资明细',
    '直接存款', '支票', '电子工资单',
    'payroll', 'payroll service', 'payroll company', 'ADP', 'Gusto',
    'wages', 'salary', 'direct deposit', 'withholding', 'paycheck',
  ],
  'finance-business-consulting': [
    '商业咨询', '创业', '开店', '做生意', '生意', '创业咨询',
    '商业计划', '商业计划书', '可行性分析', '市场调研',
    '开餐馆', '开超市', '开奶茶店', '开美甲店', '开理发店',
    '注册公司', '开公司', 'LLC', '公司注册', '营业执照',
    '牌照', '许可证', '餐馆许可', '卫生许可', '酒牌',
    '选址', '店面', '租店面', '商铺', '商业租约',
    '融资', '找投资', '天使投资', '风投',
    '小企业', 'SBA', '小企业贷款', '政府补助', '政府贷款',
    '加盟', '特许经营', '连锁', '品牌授权',
    'business consulting', 'startup', 'start a business', 'business plan',
    'small business', 'SBA loan', 'franchise', 'entrepreneur', 'LLC formation',
    'business license', 'permit', 'business advisor',
  ],

  // ═══ REAL ESTATE ═══
  'real-estate': [
    '地产', '房产', '房屋', '房子', '找房', '看房',
    '买房', '买房子', '想买房', '第一次买房', '新手买房', '买房流程',
    '租房', '租房子', '找租房', '租公寓', '短租', '长租',
    '卖房', '卖房子', '挂牌', '上市',
    '华人地产', '中文房产', '中文地产',
    '法拉盛房产', '皇后区租房', '曼哈顿租房', '布鲁克林',
    '公寓', 'condo', 'co-op', '合作公寓', '独栋', '别墅', '联排', 'townhouse',
    '房价', '房价走势', '房市', '学区房', '好学区',
    'real estate', 'property', 'housing', 'home', 'house', 'apartment',
    'buy house', 'rent apartment', 'for sale', 'for rent', 'listing',
  ],
  'realestate-agent': [
    '地产经纪', '经纪人', '房产中介', '地产中介', '找经纪', '好经纪', '经纪推荐',
    '买房中介', '卖房中介', '租房中介', '买房经纪', '卖房经纪',
    '华人经纪', '中文经纪', '说中文的经纪',
    '看房', '带看', '陪看房', '约看房',
    '佣金', '中介费', '经纪费', '买方代理', '卖方代理',
    '房源', '新房源', '独家房源', 'MLS',
    'realtor', 'real estate agent', 'real estate broker', 'broker',
    'buyer agent', 'seller agent', 'listing agent', 'Chinese realtor',
    'commission', 'showing', 'open house',
  ],
  'realestate-property-mgmt': [
    '物业', '物业管理', '管理公司', '物业公司', '找物业',
    '出租管理', '代管', '房屋托管', '出租托管', '收租',
    '租客', '找租客', '筛选租客', '租客背景调查',
    '维修', '报修', '维护', '房屋维修',
    '物业费', '管理费', 'HOA', '大楼管理',
    '租约', '续租', '退租', '驱逐', '催租',
    'property management', 'property manager', 'landlord', 'rental management',
    'tenant screening', 'rent collection', 'maintenance', 'HOA',
    'building management', 'superintendent',
  ],
  'realestate-home-inspection': [
    '验房', '验房师', '找验房', '验房推荐', '验房费用',
    '房屋检查', '房屋检测', '验屋', '买房验房', '新房验房',
    '检查报告', '验房报告', '问题房',
    '白蚁', '白蚁检查', '霉菌', '霉菌检测', '石棉', '铅漆',
    '水管', '电路', '屋顶', '地基', '结构', '房屋结构',
    '暖气', '空调', '管道', '下水道',
    'home inspection', 'home inspector', 'house inspection',
    'inspection report', 'termite', 'mold', 'radon', 'asbestos',
    'structural', 'foundation', 'plumbing inspection', 'electrical inspection',
  ],
  'realestate-commercial': [
    '商业地产', '商铺', '写字楼', '仓库', '找商铺', '租商铺',
    '店面', '店铺', '门面', '出租店面', '买店面',
    '办公室', '办公空间', '共享办公', 'coworking',
    '商场', '购物中心', '商业中心',
    '工业', '厂房', '工厂', '仓储', '配送中心',
    '商业租约', '商业地产经纪', '商铺投资',
    '餐馆转让', '美甲店转让', '超市转让', '生意转让',
    'commercial real estate', 'commercial property', 'office space',
    'retail space', 'warehouse', 'storefront', 'for lease',
    'commercial lease', 'business for sale',
  ],
  'realestate-title-closing': [
    '过户', '房屋过户', '过户律师', '找过户律师', '过户流程',
    '产权', '产权调查', '产权保险', '产权公司',
    '交割', '成交', '签约', 'closing day', '交房',
    '过户费', '过户费用', 'closing cost', '过户成本',
    '地契', '房契', '转名', '加名', '改名',
    '贷款过户', '现金过户', '全款',
    'title', 'title company', 'title search', 'title insurance',
    'closing', 'closing attorney', 'settlement', 'deed', 'deed transfer',
    'escrow', 'closing cost',
  ],
  'realestate-appraisal': [
    '估价', '评估', '房产评估', '房屋估价', '找估价',
    '评估师', '估价师', '房产估价师',
    '市场价', '公允价值', '评估价', '比较价',
    '银行估价', '贷款估价', '再融资估价',
    '税务评估', '地税评估', '地税', '申诉地税', '地税减免',
    '比较市场分析', 'CMA', '周边房价',
    'appraisal', 'appraiser', 'home appraisal', 'property appraisal',
    'market value', 'assessment', 'tax assessment', 'CMA',
    'comparable', 'comps', 'fair market value',
  ],

  // ═══ EDUCATION ═══
  'education': [
    '教育', '学校', '学习', '上课', '培训', '找学校', '找培训',
    '教育机构', '培训机构', '培训班', '兴趣班', '课外班',
    '小孩', '孩子', '儿童', '学生', '青少年',
    '暑期', '暑假班', '暑期项目', '夏令营', '冬令营',
    '华人学校', '中文学校', '周末学校',
    'education', 'school', 'learning', 'class', 'program', 'training',
    'after school', 'summer camp', 'enrichment', 'academy',
  ],
  'edu-tutoring': [
    '补习', '辅导', '补习班', '辅导班', '找补习', '补习推荐',
    '课后辅导', '课后班', '放学后', '功课辅导',
    '家教', '请家教', '一对一', '小班', '一对一辅导', '上门家教',
    '补课', '作业', '学业', '作业辅导', '写作业',
    '数学', '英语', '科学', '阅读', '写作', '语文',
    '小学', '初中', '高中', '中学',
    '成绩', '提高成绩', '学习差', '跟不上', '提分',
    '奥数', '数学竞赛', 'AMC', 'MATHCOUNTS',
    'tutoring', 'tutor', 'after school', 'homework help', 'academic tutoring',
    'math tutor', 'English tutor', 'science tutor', 'one-on-one', 'small group',
    'Kumon', 'Sylvan', 'learning center',
  ],
  'edu-language': [
    '语言', '语言学校', '语言培训', '找语言学校',
    '学英语', '英语班', '英语课', '英语培训', '英语学校', '英文班',
    '成人英语', '零基础英语', '口语', '英语口语', '会话',
    'ESL', 'ESL课程', 'ESL学校', '英语作为第二语言',
    '学中文', '中文班', '中文学校', '中文课', '普通话', '汉语', '识字',
    '拼音', '认字', '写字', '中文阅读',
    '翻译', '口译', '考翻译', '翻译培训',
    '日语', '韩语', '法语', '西班牙语',
    '公民考试英语', '入籍英语', '面试英语', '职场英语',
    'language school', 'ESL', 'English class', 'English school',
    'Chinese school', 'Mandarin class', 'language learning', 'ESOL',
    'adult English', 'beginner English', 'conversation class',
  ],
  'edu-test-prep': [
    '考试', '考试培训', '考试辅导', '备考', '考前', '找考试培训',
    'SAT', 'SAT培训', 'SAT辅导', 'SAT补习',
    'ACT', 'ACT培训', 'ACT辅导',
    'GRE', 'GMAT', 'LSAT', 'MCAT', '研究生考试',
    'TOEFL', '托福', '托福培训', '雅思', 'IELTS', '雅思培训',
    'AP', 'AP课程', 'AP考试', 'AP补习', 'IB',
    'SHSAT', '特殊高中', '特殊高中考试', 'Regents',
    '模考', '刷题', '真题', '考试技巧', '提分',
    'test prep', 'test preparation', 'SAT prep', 'ACT prep',
    'TOEFL prep', 'GRE prep', 'exam prep', 'standardized test',
    'SHSAT prep', 'AP prep', 'college entrance exam',
  ],
  'edu-music-art': [
    '音乐', '学音乐', '音乐课', '音乐学校', '音乐培训', '找音乐老师',
    '钢琴', '学钢琴', '钢琴课', '钢琴老师', '钢琴教师',
    '小提琴', '学小提琴', '大提琴', '中提琴', '弦乐',
    '吉他', '学吉他', '尤克里里', '贝斯',
    '声乐', '唱歌', '学唱歌', '合唱', '声乐老师',
    '乐器', '学乐器', '鼓', '架子鼓', '长笛', '萨克斯', '二胡', '古筝', '琵琶',
    '美术', '学画画', '画画', '绘画', '素描', '水彩', '油画', '国画',
    '书法', '学书法', '毛笔', '硬笔', '中国书法',
    '陶艺', '手工', '手工课', '创意美术',
    '考级', '考证', '音乐考级', '美术考级', 'ABRSM',
    'music', 'music lesson', 'piano', 'piano lesson', 'violin', 'guitar',
    'art', 'art class', 'drawing', 'painting', 'calligraphy', 'music school',
    'vocal', 'singing', 'instrument', 'drum',
  ],
  'edu-daycare': [
    '托管', '托管班', '课后托管', '放学后托管', '找托管',
    '托儿所', '日托', '全日托', '半日托', '找日托',
    '课后班', '课后接送', '放学接送', '接孩子',
    '保姆', '看小孩', '带小孩', '照看孩子',
    '暑期托管', '假期托管', '寒假托管',
    '作业辅导', '吃饭', '午餐', '零食',
    '安全', '有执照', '监控', '师生比',
    'daycare', 'day care', 'child care', 'childcare', 'after school care',
    'after school program', 'babysitter', 'nanny',
    'summer program', 'before school', 'pick up', 'drop off',
  ],
  'edu-stem': [
    '编程', '学编程', '编程课', '编程培训', '少儿编程', '儿童编程',
    '科技', 'STEM', 'STEM课程', 'STEM教育',
    '机器人', '乐高', '乐高机器人', 'LEGO', '机器人编程',
    '人工智能', 'AI', '人工智能课',
    '数学竞赛', '奥数', '奥数班', 'AMC', 'MATHCOUNTS', '数学培训',
    'Python', 'Java', 'Scratch', '游戏开发', 'app开发', '网页制作',
    '3D打印', '电子', '电路', '科学实验',
    '比赛', '科技比赛', '科学展', 'science fair',
    'coding', 'programming', 'robotics', 'STEM', 'computer science',
    'coding class', 'kids coding', 'Scratch', 'Python for kids',
    'math competition', 'math olympiad', 'science camp',
  ],
  'edu-sports': [
    '体育', '运动', '体育培训', '运动课', '找体育班',
    '武术', '功夫', '中国武术', '太极', '太极拳', '咏春',
    '跆拳道', '空手道', '柔道', '巴西柔术', '拳击', '散打', '搏击',
    '游泳', '学游泳', '游泳课', '游泳队', '游泳池',
    '篮球', '篮球训练', '篮球课', '篮球队',
    '足球', '足球训练', '足球课', '足球队',
    '乒乓球', '乒乓球课', '乒乓球馆', '乒乓球训练',
    '羽毛球', '网球', '棒球', '排球', '高尔夫',
    '滑冰', '花样滑冰', '冰球', '轮滑', '滑板',
    '击剑', '射箭', '攀岩', '体操', '田径', '跑步',
    'sports', 'martial arts', 'taekwondo', 'karate', 'kung fu', 'tai chi',
    'swimming', 'basketball', 'soccer', 'tennis', 'table tennis',
    'fencing', 'gymnastics', 'boxing', 'judo', 'sports training',
  ],
  'edu-dance': [
    '舞蹈', '跳舞', '学跳舞', '舞蹈课', '舞蹈培训', '舞蹈学校', '找舞蹈班',
    '芭蕾', '芭蕾舞', '学芭蕾', '芭蕾课',
    '民族舞', '中国舞', '古典舞', '民间舞', '秧歌',
    '拉丁舞', '拉丁', '恰恰', '伦巴', '桑巴',
    '街舞', 'hip hop', '爵士舞', 'jazz', '现代舞', '当代舞',
    '国标', '国标舞', '交谊舞', '社交舞', '华尔兹', '探戈',
    '肚皮舞', '印度舞', 'Bollywood',
    '成人舞蹈', '儿童舞蹈', '少儿舞蹈', '幼儿舞蹈',
    '考级', '舞蹈考级', '比赛', '舞蹈比赛', '演出',
    'dance', 'dance class', 'dance school', 'ballet', 'Latin dance',
    'hip hop dance', 'jazz dance', 'modern dance', 'ballroom',
    'kids dance', 'adult dance', 'Zumba',
  ],
  'edu-driving-school': [
    '驾校', '学车', '找驾校', '驾校推荐', '驾校排名',
    '考驾照', '拿驾照', '驾照', '驾驶执照',
    '练车', '学开车', '新手学车', '零基础学车',
    '路考', '路考技巧', '路考攻略', '几次过',
    '笔试', '科目一', '理论考试', '交规',
    '驾驶', '开车', '教练', '驾校教练', '中文教练',
    '包过', '多久拿照', '学费多少', '几节课',
    '华人驾校', '中文驾校', '说中文的教练',
    '自动挡', '手动挡', '练习场', '模拟',
    'driving school', "driver's license", 'driving lesson', 'driving test',
    'road test', 'permit test', 'learn to drive', 'driving instructor',
    'Chinese driving school', 'DMV', '5-hour course',
  ],
  'edu-preschool': [
    '幼儿园', '学前班', '找幼儿园', '幼儿园推荐', '好幼儿园',
    'pre-K', 'PreK', '免费PreK', 'UPK', '3K', '3岁', '4岁',
    '幼教', '早教', '早教中心', '蒙特梭利', 'Montessori',
    '入园', '报名', '申请', '面试', '等位', '候补',
    '双语', '双语幼儿园', '中文幼儿园', '中英双语',
    '师资', '师生比', '课程', '户外', '安全',
    '公立', '私立', '公立幼儿园', '私立幼儿园', '教会幼儿园',
    'preschool', 'kindergarten', 'pre-K', 'UPK', '3K for all',
    'nursery school', 'early childhood', 'Montessori', 'daycare preschool',
    'bilingual preschool', 'Chinese preschool',
  ],
  'edu-college-prep': [
    '升学', '升学顾问', '升学指导', '升学规划', '找升学顾问',
    '大学申请', '申请大学', '大学录取', '大学招生',
    '留学', '出国留学', '留学咨询', '留学中介', '留学申请',
    '常春藤', '藤校', '名校', 'Ivy League', '前50', 'Top 50',
    '文书', '申请文书', '个人陈述', 'essay', 'personal statement',
    '推荐信', '课外活动', '义工', '志愿者', '实习',
    '面试', '大学面试', '面试辅导', '面试技巧',
    '奖学金', '助学金', '学费减免', 'financial aid', 'FAFSA',
    '选校', '择校', '学校排名', '专业选择',
    '纽约特殊高中', 'Stuyvesant', 'Bronx Science', '布朗克斯科学',
    'college prep', 'college counseling', 'college admission', 'college application',
    'college consultant', 'university', 'Ivy League', 'SAT prep',
    'scholarship', 'financial aid', 'study abroad',
  ],

  // ═══ HOME ═══
  'home-renovation': [
    '装修', '装修公司', '找装修', '装修推荐', '装修师傅', '装修队',
    '家居', '翻新', '改造', '旧房翻新', '房屋翻新', '局部翻新',
    '新房装修', '公寓装修', '别墅装修', '商铺装修', '办公室装修',
    '设计', '室内设计', '装修设计', '免费量房', '免费报价',
    '华人装修', '中文装修', '中国师傅',
    '预算', '装修预算', '多少钱', '报价', '估价',
    '工期', '多久', '装修时间',
    'renovation', 'home improvement', 'remodel', 'remodeling',
    'home renovation', 'contractor', 'interior design', 'Chinese contractor',
  ],
  'home-general-contractor': [
    '总承包', '承包商', '总包', '包工头', '找承包商', '装修承包',
    '工程', '建筑', '建筑公司', '施工', '施工队',
    '加建', '扩建', '改建', '阁楼', '地下室', '地下室装修', '阁楼改造',
    '新建', '盖房子', '建房子', '自建房',
    '许可证', '建筑许可', 'permit', '报批',
    '监理', '工程监理', '质量', '验收',
    'general contractor', 'GC', 'builder', 'construction', 'construction company',
    'home builder', 'basement', 'addition', 'extension', 'build',
    'licensed contractor', 'insured contractor',
  ],
  'home-plumbing': [
    '水管', '水管工', '找水管工', '水管推荐', '水管师傅',
    '管道', '管道疏通', '管道维修', '管道安装',
    '漏水', '水管漏水', '墙壁漏水', '天花板漏水', '修漏水',
    '马桶', '马桶堵了', '马桶漏水', '换马桶', '修马桶',
    '下水道', '下水道堵了', '下水道疏通', '排水', '排水不畅',
    '水龙头', '换水龙头', '水龙头漏水', '滴水',
    '热水器', '换热水器', '热水器坏了', '没热水', '锅炉',
    '厨房管道', '浴室管道', '洗碗机', '洗衣机排水',
    '紧急', '水管紧急', '爆管', '水管爆裂', '24小时',
    'plumbing', 'plumber', 'pipe', 'leak', 'drain', 'clogged',
    'toilet', 'faucet', 'water heater', 'boiler', 'sewer',
    'emergency plumber', '24 hour plumber', 'pipe repair',
  ],
  'home-electrical': [
    '电工', '找电工', '电工推荐', '电工师傅', '持牌电工',
    '电路', '电路维修', '电路安装', '布线', '走线', '明线', '暗线',
    '开关', '插座', '换开关', '加插座', '插座不够',
    '跳闸', '经常跳闸', '电路跳闸', '保险丝', '断路器', '电箱', '配电箱',
    '灯', '装灯', '换灯', '吊灯', '筒灯', '灯不亮', 'LED灯',
    '电压', '升级电路', '200安', '100安', '安培',
    '吊扇', '排风扇', '浴室排风', '厨房排风',
    '网络', '网线', '电话线', '智能家居',
    '紧急', '电路紧急', '触电', '火花', '烧焦味',
    'electrical', 'electrician', 'licensed electrician', 'wiring', 'outlet',
    'circuit breaker', 'panel upgrade', 'light fixture', 'ceiling fan',
    'electrical repair', 'switch', 'socket', 'power outage',
  ],
  'home-painting': [
    '油漆', '油漆工', '找油漆工', '油漆推荐', '油漆师傅',
    '刷墙', '粉刷', '刷漆', '涂料', '墙面', '墙面翻新',
    '内墙', '外墙', '室内粉刷', '室外粉刷', '外墙刷漆',
    '颜色', '选颜色', '配色', '色卡',
    '乳胶漆', '防水漆', '底漆', '面漆', '环保漆',
    '壁纸', '墙纸', '贴壁纸', '撕壁纸',
    '补洞', '补墙', '裂缝', '墙面裂缝', '批灰', '刮腻子',
    '天花板', '刷天花板', '喷漆',
    'painting', 'painter', 'house painter', 'interior painting', 'exterior painting',
    'wall painting', 'paint', 'wallpaper', 'drywall repair', 'skim coat',
    'staining', 'deck staining',
  ],
  'home-cleaning': [
    '清洁', '保洁', '打扫', '找保洁', '保洁推荐', '保洁阿姨',
    '深度清洁', '大扫除', '彻底清洁', '定期清洁',
    '家政', '钟点工', '按小时', '家政服务', '家政公司',
    '搬家清洁', '退租清洁', '入住清洁', '新房清洁',
    '办公室清洁', '商业清洁', '店铺清洁',
    '厨房清洁', '浴室清洁', '油烟机清洗', '冰箱清洗',
    '地毯清洗', '沙发清洗', '窗帘清洗', '窗户清洗', '玻璃清洗',
    '消毒', '除味', '甲醛', '除甲醛',
    '地板打蜡', '地板抛光', '石材保养', '大理石',
    'cleaning', 'cleaning service', 'house cleaning', 'housekeeping', 'maid',
    'maid service', 'deep cleaning', 'move-in cleaning', 'move-out cleaning',
    'carpet cleaning', 'window cleaning', 'office cleaning', 'janitorial',
  ],
  'home-moving': [
    '搬家', '搬运', '搬家公司', '找搬家', '搬家推荐', '搬家师傅',
    '长途搬家', '短途搬家', '本地搬家', '跨州搬家',
    '打包', '搬家打包', '打包材料', '纸箱', '泡沫',
    '搬钢琴', '大件搬运', '重物搬运', '家具搬运',
    '搬家价格', '多少钱', '按小时', '按车', '一车多少',
    '上楼', '没电梯', '几楼', '楼梯搬运',
    '存储', '暂存', '临时存放', '仓库',
    '华人搬家', '中国人搬家', '中文搬家',
    '垃圾清运', '旧家具处理', '丢东西',
    'moving', 'movers', 'moving company', 'local moving', 'long distance moving',
    'packing', 'piano moving', 'furniture moving', 'storage',
    'Chinese movers', 'affordable movers', 'moving truck',
  ],
  'home-hvac': [
    '暖通', '暖通工', '找暖通', 'HVAC师傅',
    '空调', '装空调', '修空调', '空调不制冷', '空调漏水', '空调清洗', '空调加氟',
    '暖气', '暖气片', '暖气不热', '没暖气', '修暖气', '暖气漏水',
    '冷气', '冷气机', '窗式空调', '分体空调', '挂机',
    '中央空调', '安装中央空调', '中央空调维修',
    '制冷', '制热', '恒温器', '温控器', 'thermostat',
    '锅炉', '换锅炉', '修锅炉', '锅炉保养', '热水锅炉', '蒸汽锅炉',
    '通风', '排风', '新风', '新风系统', '空气净化',
    '加湿器', '除湿器', '湿度',
    'HVAC', 'heating', 'AC', 'air conditioning', 'air conditioner',
    'furnace', 'boiler', 'heat pump', 'ductless', 'mini split',
    'thermostat', 'ventilation', 'HVAC repair', 'HVAC installation',
  ],
  'home-roofing': [
    '屋顶', '修屋顶', '换屋顶', '找修屋顶', '屋顶推荐',
    '漏雨', '屋顶漏水', '天花板漏水', '下雨漏水',
    '屋顶检查', '屋顶维修', '屋顶更换', '屋顶翻新',
    '瓦片', '沥青瓦', '瓦片松了', '瓦片飞了',
    '排水沟', '雨槽', '清理排水沟', '水槽堵了',
    '防水', '屋顶防水', '阳台防水', '天台防水',
    '风暴', '暴风雨', '大风', '树砸了', '保险理赔',
    '烟囱', '修烟囱', '烟囱漏水',
    'roofing', 'roof repair', 'roof replacement', 'roofer',
    'roof leak', 'shingle', 'gutter', 'waterproofing', 'flat roof',
    'roof inspection', 'storm damage', 'chimney',
  ],
  'home-flooring': [
    '地板', '铺地板', '换地板', '地板安装', '找铺地板',
    '地砖', '铺地砖', '瓷砖', '贴瓷砖', '墙砖',
    '木地板', '实木地板', '复合地板', '强化地板', '竹地板',
    '大理石', '花岗岩', '石材', '天然石',
    '地板打磨', '翻新地板', '地板打蜡', '修地板',
    '地板变色', '地板翘起', '地板响', '地板裂',
    '地毯', '铺地毯', '换地毯', '地毯清洗',
    '防水地板', 'SPC', 'LVP', '乙烯基',
    'flooring', 'floor', 'tile', 'hardwood', 'hardwood floor',
    'laminate', 'vinyl', 'marble', 'floor installation', 'floor refinishing',
    'carpet', 'tile installation', 'grout',
  ],
  'home-landscaping': [
    '园艺', '绿化', '园林', '找园艺', '园艺推荐',
    '草坪', '割草', '修草', '草坪维护', '除草', '杂草', '施肥',
    '修剪', '修树', '砍树', '伐树', '树枝修剪', '灌木修剪',
    '花园', '庭院', '院子', '后院', '前院', '种花', '种菜', '菜园',
    '花', '种植', '花坛', '花圃', '盆栽',
    '围栏', '栅栏', '篱笆', '装围栏', '修围栏',
    '铺石', '铺路', '石板路', '水泥路', '车道', '修车道',
    '灌溉', '喷淋', '浇水', '自动浇水',
    '除雪', '铲雪', '撒盐',
    'landscaping', 'landscaper', 'gardening', 'lawn', 'lawn care', 'lawn mowing',
    'tree trimming', 'tree removal', 'garden', 'yard', 'fence',
    'patio', 'driveway', 'snow removal', 'irrigation', 'mulch',
  ],
  'home-pest-control': [
    '害虫', '灭虫', '除虫', '杀虫', '灭害', '找灭虫', '灭虫推荐',
    '蟑螂', '灭蟑螂', '蟑螂多', '小强', '德国蟑螂',
    '老鼠', '灭鼠', '老鼠多', '老鼠洞', '老鼠屎', '捕鼠',
    '白蚁', '白蚁防治', '白蚁检查', '白蚁处理',
    '蚂蚁', '灭蚂蚁', '蜘蛛', '蜈蚣', '蝎子',
    '臭虫', '床虱', '灭臭虫', 'bed bug', '被咬', '身上痒',
    '跳蚤', '灭跳蚤', '宠物跳蚤',
    '蚊子', '苍蝇', '飞虫', '果蝇',
    '黄蜂', '马蜂', '蜂窝', '蜜蜂', '摘蜂窝',
    '定期灭虫', '包月', '季度灭虫',
    'pest control', 'exterminator', 'bug', 'roach', 'cockroach',
    'mouse', 'rat', 'mice', 'termite', 'bed bug', 'ant',
    'flea', 'mosquito', 'wasp', 'pest removal',
  ],
  'home-locksmith': [
    '锁匠', '找锁匠', '锁匠推荐', '附近锁匠',
    '换锁', '换门锁', '换锁芯', '换锁多少钱',
    '开锁', '锁门外面了', '被锁门外', '钥匙丢了', '紧急开锁',
    '配钥匙', '复制钥匙', '多配钥匙',
    '门锁', '智能锁', '密码锁', '指纹锁', '电子锁', '安装智能锁',
    '保险箱', '打不开', '保险柜',
    '车锁', '车钥匙', '车钥匙锁车里了',
    '防盗', '防盗锁', '安全锁',
    '24小时', '紧急', '半夜', '急用',
    'locksmith', 'lock', 'key', 'lock change', 'lock out', 'locked out',
    'key copy', 'smart lock', 'deadbolt', 'emergency locksmith',
    '24 hour locksmith', 'car locksmith', 'rekey',
  ],
  'home-kitchen-bath': [
    '厨卫', '厨房装修', '浴室装修', '找厨卫装修',
    '厨房', '厨房翻新', '厨房改造', '厨房设计',
    '橱柜', '定制橱柜', '换橱柜', '橱柜安装', '橱柜台面',
    '台面', '大理石台面', '石英石台面', '花岗岩台面', 'granite',
    '浴室', '浴室翻新', '浴室改造', '浴室设计',
    '卫生间', '厕所', '洗手间',
    '淋浴', '淋浴房', '浴缸', '换浴缸', '浴缸漏水',
    '马桶', '洗手台', '洗手盆', '浴室柜', '镜子',
    '瓷砖', '墙砖', '地砖', '防水', '浴室防水',
    '水龙头', '花洒', '淋浴花洒',
    'kitchen', 'kitchen remodel', 'bathroom', 'bathroom remodel',
    'cabinet', 'countertop', 'vanity', 'shower', 'bathtub',
    'kitchen renovation', 'bathroom renovation', 'tile', 'backsplash',
  ],
  'home-windows-doors': [
    '门窗', '门窗安装', '门窗更换', '找门窗', '门窗推荐',
    '换窗', '换窗户', '窗户', '窗户坏了', '窗户漏风', '窗户漏水',
    '纱窗', '装纱窗', '纱门', '防蚊纱窗',
    '防盗门', '大门', '入户门', '换大门', '门锁',
    '室内门', '房间门', '推拉门', '折叠门', '谷仓门',
    '玻璃', '双层玻璃', '钢化玻璃', '玻璃碎了', '换玻璃',
    '百叶窗', '窗帘轨道', '遮光', '隔热',
    '隔音', '隔音窗', '噪音', '降噪',
    '节能', '节能窗', '保温',
    'windows', 'doors', 'window replacement', 'door installation',
    'screen door', 'storm door', 'sliding door', 'French door',
    'window repair', 'glass', 'double pane', 'energy efficient window',
  ],
  'home-furniture': [
    '家具', '买家具', '家具店', '找家具', '家具推荐',
    '沙发', '买沙发', '布沙发', '皮沙发', '转角沙发',
    '床', '床垫', '买床', '双人床', '上下铺', '儿童床',
    '桌子', '餐桌', '书桌', '办公桌', '茶几', '电脑桌',
    '柜子', '衣柜', '鞋柜', '书柜', '电视柜', '收纳柜', '储物柜',
    '椅子', '办公椅', '餐椅', '躺椅', '摇椅',
    '家居用品', '家居装饰', '灯具', '地毯', '窗帘',
    '定制家具', '实木家具', '中式家具', '现代家具',
    '二手家具', '旧家具', '处理家具', '捐家具',
    '送货', '安装', '组装', '家具安装',
    'IKEA', '宜家', 'Ashley', 'Wayfair',
    'furniture', 'furniture store', 'sofa', 'couch', 'bed', 'mattress',
    'table', 'desk', 'chair', 'cabinet', 'dresser', 'bookshelf',
    'custom furniture', 'delivery', 'assembly',
  ],

  // ═══ BEAUTY ═══
  'beauty-wellness': [
    '美容', '保健', '养生', '美容保健', '找美容', '美容推荐',
    '护理', '身体护理', '面部护理', '个人护理',
    '减压', '放松', '休闲', '舒压',
    '华人美容', '中文美容', '中国人开的',
    'beauty', 'wellness', 'self care', 'beauty salon', 'spa', 'relaxation',
  ],
  'beauty-hair-salon': [
    '美发', '美发店', '找美发', '美发推荐', '美发师',
    '理发', '剪头发', '剪发', '剪头', '修剪',
    '烫发', '烫头发', '卷发', '直发', '拉直', '离子烫', '冷烫', '热烫', '数码烫',
    '染发', '染头发', '漂发', '挑染', '挂耳染', '渐变色', '补染', '黑色', '棕色',
    '发型', '发型设计', '造型', '吹风造型', '盘发', '编发',
    '发廊', '头发', '发型师', '总监', '设计师',
    '洗剪吹', '护理', '头发护理', '焗油', '发膜', '头皮护理',
    '接发', '假发', '补发',
    '婚礼造型', '新娘发型', '毕业照', '证件照造型',
    'hair salon', 'haircut', 'hairstyle', 'hair stylist', 'hairdresser',
    'perm', 'hair color', 'highlights', 'balayage', 'keratin',
    'blowout', 'hair treatment', 'Chinese hair salon',
  ],
  'beauty-barber': [
    '理发', '理发店', '找理发', '理发推荐',
    '男士理发', '男士发型', '男士造型', '剃头',
    '刮胡子', '修面', '刮脸', '修胡子',
    '寸头', '平头', '圆寸', '背头', '飞机头', 'fade', '渐变', '铲青',
    '剃光头', '光头', '推子', '电推',
    '儿童理发', '小孩理发', '宝宝理发',
    '多少钱', '不用预约', '排队',
    'barber', 'barbershop', 'barber shop', 'men haircut', 'fade',
    'shave', 'beard trim', 'buzz cut', 'taper',
    'kids haircut', 'walk-in', 'cheap haircut',
  ],
  'beauty-nail-salon': [
    '美甲', '美甲店', '做指甲', '找美甲', '美甲推荐',
    '指甲', '指甲油', '甲油', '甲油胶', '光疗', '光疗甲',
    '修甲', '手部护理', '手膜',
    '脚部', '足部', '脚指甲', '修脚', '足部护理',
    '法式', '法式美甲', '日式', '日式美甲', '手绘', '贴钻', '晕染',
    '延长甲', '水晶甲', '甲片', '穿戴甲',
    '卸甲', '卸光疗', '补甲',
    '美睫', '种睫毛', '接睫毛', '嫁接睫毛', '睫毛',
    '蜡脱毛', '脱毛', '手部脱毛', '腿部脱毛', '热蜡',
    'nail salon', 'nails', 'manicure', 'pedicure', 'gel', 'gel nails',
    'acrylic nails', 'nail art', 'dip powder', 'shellac',
    'eyelash extensions', 'lash', 'waxing',
  ],
  'beauty-spa-massage': [
    'SPA', '水疗', '水疗中心', '找SPA', 'SPA推荐',
    '按摩', '推拿', '全身按摩', '局部按摩', '肩颈按摩', '背部按摩',
    '足疗', '足浴', '脚底按摩', '足底按摩', '泡脚',
    '推油', '精油按摩', '精油', '香薰', '芳疗', '芳香疗法',
    '泰式按摩', '日式按摩', '瑞典式', '深层组织', '热石',
    '刮痧', '拔罐', '中式按摩', '传统按摩',
    '夫妻按摩', '情侣SPA', '双人间',
    '温泉', '桑拿', '蒸汽', '汗蒸', '盐房',
    '放松', '减压', '舒缓', '疲劳', '酸痛',
    'spa', 'massage', 'foot massage', 'body massage', 'deep tissue',
    'Swedish massage', 'hot stone', 'Thai massage', 'reflexology',
    'couples massage', 'sauna', 'steam room', 'relaxation',
  ],
  'beauty-skincare': [
    '美容', '护肤', '皮肤管理', '面部护理', '找美容', '美容推荐',
    '面部', '脸部', '面膜', '补水', '保湿',
    '美白', '淡斑', '祛斑', '雀斑', '色斑', '暗沉',
    '抗衰', '抗老', '抗皱', '皱纹', '细纹', '紧致', '提拉',
    '痘痘', '祛痘', '粉刺', '黑头', '毛孔', '清洁毛孔',
    '小气泡', '水光', '果酸', '刷酸', '去角质',
    '光子嫩肤', 'IPL', '射频', '超声刀', 'HIFU',
    '眼部', '黑眼圈', '眼袋', '泪沟',
    '敏感肌', '红血丝', '修复', '屏障修复',
    'skincare', 'facial', 'skin care', 'facial treatment',
    'anti-aging', 'acne treatment', 'whitening', 'hydrating',
    'microdermabrasion', 'chemical peel', 'LED therapy',
  ],
  'beauty-fitness-gym': [
    '健身', '健身房', '找健身房', '健身房推荐', '办健身卡',
    '运动', '锻炼', '健身课', '团课', '私教', '私人教练', '教练',
    '减肥', '瘦身', '减脂', '甩肉', '控制体重',
    '增肌', '增重', '塑形', '马甲线', '腹肌',
    '力量训练', '撸铁', '举重', '哑铃', '杠铃',
    '有氧', '跑步', '跑步机', '动感单车', '椭圆机',
    '游泳', '游泳池', '室内游泳',
    '拳击', '搏击', '搏击操',
    '瑜伽', '普拉提', '有氧操', 'Zumba', '尊巴',
    'CrossFit', '功能训练', 'HIIT', '间歇训练',
    '月卡', '年卡', '会员', '价格', '多少钱',
    '24小时', '24小时健身房', 'Planet Fitness', 'Equinox', 'Blink',
    'gym', 'fitness', 'workout', 'exercise', 'personal trainer',
    'weight loss', 'muscle', 'strength training', 'cardio',
    'fitness class', 'gym membership', 'CrossFit',
  ],
  'beauty-yoga-pilates': [
    '瑜伽', '瑜伽馆', '瑜伽课', '学瑜伽', '找瑜伽', '瑜伽推荐',
    '热瑜伽', '高温瑜伽', 'Bikram', '阴瑜伽', '流瑜伽', 'Vinyasa', '哈他', 'Hatha',
    '空中瑜伽', '反重力瑜伽', '瑜伽轮', '瑜伽球',
    '普拉提', '普拉提课', '器械普拉提', '大器械', 'reformer',
    '冥想', '打坐', '正念', '呼吸', '呼吸法', '放松',
    '拉伸', '柔韧', '筋骨', '开肩', '开髋',
    '孕妇瑜伽', '产后瑜伽', '儿童瑜伽', '亲子瑜伽',
    '初学者', '零基础', '入门', '体验课',
    '教练培训', '瑜伽教练', 'RYT', '200小时',
    'yoga', 'yoga studio', 'yoga class', 'pilates', 'Pilates studio',
    'meditation', 'hot yoga', 'vinyasa', 'hatha', 'aerial yoga',
    'reformer Pilates', 'mindfulness', 'stretching',
  ],
  'beauty-tattoo': [
    '纹身', '纹身店', '找纹身', '纹身推荐', '纹身师',
    '文身', '刺青', '纹身设计', '定制纹身', '原创纹身',
    '小纹身', '大图', '彩色', '黑灰', '水彩', '写实', '传统', '日式',
    '遮盖', '纹身遮盖', '改纹身', '洗纹身', '激光洗纹身',
    '纹眉', '雾眉', '线条眉', '野生眉', '眉毛',
    '纹唇', '漂唇', '嘟嘟唇',
    '纹眼线', '美瞳线',
    '半永久', '半永久化妆', '半永久纹绣',
    '发际线', '纹发际线', '头皮纹绣',
    'tattoo', 'tattoo shop', 'tattoo artist', 'tattoo parlor',
    'microblading', 'permanent makeup', 'eyebrow tattoo', 'lip tattoo',
    'tattoo removal', 'cover up', 'custom tattoo',
  ],
  'beauty-medical-aesthetics': [
    '医美', '医美诊所', '找医美', '医美推荐', '医美医生',
    '整形', '微整形', '整容', '整形外科',
    '注射', '打针', '注射美容',
    '玻尿酸', '打玻尿酸', '填充', '丰唇', '丰下巴', '泪沟填充', '法令纹',
    '肉毒素', 'Botox', '瘦脸针', '除皱针', '抬头纹', '鱼尾纹', '咬肌',
    '激光', '激光美容', '点痣', '祛斑', '嫩肤', '紧肤',
    '超声刀', 'HIFU', '热玛吉', 'Thermage', '射频',
    '光子嫩肤', 'IPL', 'BBL',
    '线雕', '埋线', '提升', '面部提升',
    '双眼皮', '割双眼皮', '开眼角', '眼袋', '去眼袋',
    '隆鼻', '鼻综合', '鼻整形',
    '吸脂', '抽脂', '溶脂', '酷塑', 'CoolSculpting',
    '脱毛', '激光脱毛', '全身脱毛', '冰点脱毛',
    'medical aesthetics', 'med spa', 'medspa', 'cosmetic', 'plastic surgery',
    'Botox', 'filler', 'dermal filler', 'laser', 'injection',
    'facelift', 'liposuction', 'CoolSculpting', 'microneedling', 'PRP',
    'lip filler', 'double eyelid', 'rhinoplasty', 'laser hair removal',
  ],

  // ═══ AUTO ═══
  'auto': [
    '汽车', '车', '修车', '汽车服务', '找修车', '汽车推荐',
    '华人修车', '中文修车', '中国人修车',
    '车坏了', '车有问题', '检查车', '汽车检查',
    'auto', 'car', 'vehicle', 'auto service', 'car service',
  ],
  'auto-repair': [
    '汽车维修', '修车', '汽修', '汽修店', '找修车', '修车推荐', '修车师傅',
    '发动机', '引擎', '发动机灯', 'check engine', '引擎故障',
    '刹车', '刹车片', '刹车盘', '刹车油', '刹车响', '刹不住',
    '变速箱', '变速箱油', '换挡', '自动变速箱', '手动变速箱',
    '电池', '电瓶', '打不着火', '启动不了', '搭电', '跳线',
    '空调', '车载空调', '空调不制冷', '加氟',
    '排气', '排气管', '消声器', '尾气', '年检', '检测', 'inspection',
    '水箱', '冷却液', '过热', '水温高',
    '悬挂', '减震', '底盘', '异响', '方向盘', '跑偏',
    '正时皮带', '皮带', '水泵', '发电机', '启动马达',
    '诊断', '电脑诊断', 'OBD', '故障码',
    'auto repair', 'mechanic', 'auto shop', 'car repair', 'engine',
    'brake', 'transmission', 'battery', 'AC repair', 'exhaust',
    'suspension', 'check engine light', 'diagnostic',
  ],
  'auto-body-shop': [
    '钣金', '钣金喷漆', '找钣金', '钣金推荐',
    '喷漆', '补漆', '全车喷漆', '局部补漆', '刮花', '划痕',
    '车身修复', '车身维修', '凹陷修复', '凹痕', '免喷漆修复', 'PDR',
    '事故车', '事故维修', '撞车', '被撞', '追尾',
    '保险理赔', '保险修车', '走保险', '定损',
    '保险杠', '前保险杠', '后保险杠', '换保险杠',
    '车门', '换车门', '车门凹了',
    '挡风玻璃', '玻璃碎了', '换玻璃', '裂缝',
    '防锈', '底盘防锈', '车身防锈',
    'body shop', 'auto body', 'collision repair', 'paint', 'dent repair',
    'accident repair', 'bumper', 'fender', 'insurance claim',
    'PDR', 'paintless dent repair', 'windshield', 'scratch repair',
  ],
  'auto-dealer': [
    '车行', '买车', '卖车', '找车行', '车行推荐',
    '二手车', '二手车行', '买二手车', '卖二手车', '靠谱二手车',
    '新车', '买新车', '新车优惠', '新车价格',
    '车商', '经销商', '4S店',
    '华人车行', '中文车行', '中国人车行',
    '贷款买车', '车贷', '零首付', '分期', '月供', '利率',
    '过户', '车辆过户', '转名', 'title transfer',
    '试驾', '看车', '验车', '查车', 'Carfax',
    '丰田', '本田', '奔驰', 'BMW', '宝马', '特斯拉', 'Tesla', '日产', '现代',
    '以旧换新', '置换', 'trade in',
    'auto dealer', 'car dealer', 'car dealership', 'used car', 'new car',
    'buy car', 'sell car', 'pre-owned', 'certified pre-owned',
    'car loan', 'financing', 'lease', 'test drive',
  ],
  'auto-tire': [
    '轮胎', '换轮胎', '换胎', '找换轮胎', '轮胎推荐',
    '补胎', '轮胎破了', '轮胎漏气', '扎钉子', '爆胎',
    '轮毂', '轮圈', '钢圈', '铝合金轮毂',
    '四轮定位', '动平衡', '轮胎平衡', '跑偏',
    '雪胎', '冬季轮胎', '全季轮胎', '夏季轮胎', '换季',
    '轮胎品牌', '米其林', '普利司通', '固特异', '大陆',
    '轮胎尺寸', '轮胎型号', '多少钱',
    'tire', 'tires', 'tire shop', 'tire change', 'flat tire',
    'tire repair', 'wheel', 'alignment', 'balancing', 'winter tires',
    'snow tires', 'tire rotation', 'Michelin', 'Bridgestone',
  ],
  'auto-car-wash': [
    '洗车', '洗车店', '找洗车', '洗车推荐',
    '汽车美容', '车身美容', '打蜡', '抛光', '镀膜', '镀晶',
    '内饰清洁', '内饰清洗', '座椅清洗', '皮革保养',
    '手洗', '机洗', '自动洗车', '手工洗车', '精洗',
    '贴膜', '车窗贴膜', '隔热膜', '太阳膜', '车身改色',
    '除味', '臭氧消毒', '车内消毒',
    'car wash', 'auto detailing', 'detailing', 'wax', 'polish',
    'ceramic coating', 'interior cleaning', 'hand wash',
    'window tinting', 'paint protection', 'PPF',
  ],
  'auto-towing': [
    '拖车', '叫拖车', '找拖车', '拖车公司', '拖车电话',
    '救援', '道路救援', '紧急救援', '24小时救援',
    '抛锚', '车抛锚', '路上抛锚', '车坏在路上',
    '搭电', '跳线', '电瓶没电', '打不着火',
    '换胎', '路边换胎', '备胎',
    '送油', '没油了', '加油',
    '解锁', '钥匙锁车里',
    '事故拖车', '长途拖车', '异地拖车',
    'towing', 'tow truck', 'roadside assistance', 'breakdown',
    'jump start', 'flat tire', 'lockout', 'fuel delivery',
    '24 hour towing', 'emergency towing', 'AAA',
  ],
  'auto-oil-change': [
    '换机油', '换油', '机油', '找换机油', '换机油推荐',
    '保养', '汽车保养', '定期保养', '常规保养', '大保养', '小保养',
    '机油', '全合成', '半合成', '矿物油', '机油品牌',
    '滤芯', '机油滤芯', '空气滤芯', '空调滤芯', '燃油滤芯',
    '变速箱油', '刹车油', '冷却液', '防冻液', '转向油',
    '火花塞', '换火花塞', '雨刮', '换雨刮',
    '多久换', '多少公里', '几个月', '保养手册',
    '快速换油', '不用预约', '等候', '多少钱',
    'oil change', 'lube', 'maintenance', 'car maintenance', 'synthetic oil',
    'oil filter', 'air filter', 'fluid change', 'brake fluid',
    'transmission fluid', 'coolant', 'spark plug', 'wiper',
    'Jiffy Lube', 'Valvoline', 'quick lube',
  ],

  // ═══ OTHER SERVICES ═══
  'other-services': [
    '服务', '其他', '其他服务', '生活服务', '找服务',
    '华人服务', '中文服务', '便民服务',
    'service', 'other service', 'local service',
  ],
  'svc-travel': [
    '旅行', '旅行社', '旅游', '找旅行社', '旅行社推荐',
    '机票', '买机票', '打折机票', '便宜机票', '回国机票', '中国机票', '特价',
    '签证', '旅游签证', '签证代办', '加急签证',
    '酒店', '订酒店', '酒店预订', '民宿', 'Airbnb',
    '旅游团', '跟团', '自由行', '半自由行', '华人旅游团',
    '一日游', '周边游', '东海岸', '西海岸', '尼亚加拉', '黄石', '大峡谷',
    '回国', '回中国', '直飞', '转机', '行李', '超重',
    '邮轮', '游轮', '加勒比', '巴哈马',
    '租车', '自驾', '租车公司',
    'travel', 'travel agency', 'travel agent', 'flight', 'airline ticket',
    'hotel', 'tour', 'vacation', 'cruise', 'car rental',
    'China flight', 'cheap flight', 'package tour', 'group tour',
  ],
  'svc-shipping': [
    '快递', '寄快递', '国际快递', '找快递', '快递推荐',
    '物流', '物流公司', '货运', '运输',
    '寄包裹', '寄东西', '寄回国', '寄到中国', '寄美国',
    '海运', '海运回国', '海运集装箱', '拼箱', '整箱',
    '空运', '空运快递', '航空快递',
    '报关', '清关', '关税', '海关', '进口', '出口',
    '搬家回国', '海运搬家', '国际搬家',
    '代购', '转运', '代收', '集运',
    '多久到', '时效', '价格', '按磅', '按体积',
    '华人快递', '中国快递', '华人物流',
    'shipping', 'international shipping', 'logistics', 'package', 'parcel',
    'ship to China', 'ocean freight', 'air freight', 'cargo',
    'customs', 'FedEx', 'UPS', 'USPS', 'DHL', 'courier',
  ],
  'svc-photography': [
    '摄影', '摄影师', '找摄影', '摄影推荐',
    '拍照', '拍照片', '照相', '照相馆',
    '写真', '个人写真', '艺术照', '形象照', '职业照',
    '婚纱照', '婚礼摄影', '婚礼摄像', '婚礼跟拍',
    '证件照', '护照照片', '签证照片', '2寸照', '美签照',
    '全家福', '亲子照', '宝宝照', '百天照', '满月照', '周岁照',
    '毕业照', '毕业典礼', '毕业摄影',
    '摄像', '视频制作', '视频拍摄', '宣传片', '短视频', 'Vlog',
    '活动摄影', '商业摄影', '产品摄影', '美食摄影',
    '修图', 'PS', '后期', '精修',
    'photography', 'photographer', 'photo', 'photo studio',
    'wedding photography', 'portrait', 'headshot', 'passport photo',
    'videography', 'videographer', 'video production', 'event photography',
  ],
  'svc-printing': [
    '印刷', '印刷公司', '打印', '打印店', '找印刷', '印刷推荐',
    '名片', '印名片', '名片设计', '名片制作',
    '传单', '宣传单', 'flyer', '传单印刷', '传单设计',
    '海报', '印海报', '大幅海报', '展板',
    '设计', '平面设计', 'logo', '标志设计', '品牌设计',
    '横幅', '条幅', '横幅印刷', 'banner', '旗帜',
    '菜单', '印菜单', '菜单设计', '餐厅菜单',
    '标签', '不干胶', '贴纸', '标牌', '招牌',
    '复印', '扫描', '传真', '装订', '过塑',
    '请帖', '邀请函', '婚礼请帖', '生日请帖',
    'T恤', '文化衫', '定制T恤', '定制服装',
    'printing', 'print shop', 'design', 'graphic design', 'banner',
    'business card', 'flyer', 'poster', 'brochure', 'sign', 'signage',
    'menu printing', 'custom printing', 'sticker', 'label',
  ],
  'svc-translation': [
    '翻译', '翻译公司', '找翻译', '翻译推荐', '翻译价格',
    '口译', '口译员', '现场口译', '陪同翻译', '会议口译',
    '笔译', '文件翻译', '资料翻译', '合同翻译',
    '同声传译', '同传', '交替传译',
    '中英翻译', '英中翻译', '中文翻译', '英文翻译',
    '证件翻译', '出生证翻译', '结婚证翻译', '学历翻译', '成绩单翻译',
    '法律翻译', '医疗翻译', '商业翻译', '技术翻译',
    '公证翻译', '认证翻译', '官方翻译',
    '移民翻译', '签证翻译', '法庭翻译',
    '网站翻译', '本地化', '字幕翻译',
    'translation', 'translator', 'interpreter', 'interpreting',
    'Chinese translation', 'English translation', 'document translation',
    'certified translation', 'legal translation', 'medical translation',
    'simultaneous interpretation', 'court interpreter',
  ],
  'svc-pet': [
    '宠物', '宠物店', '找宠物', '宠物推荐',
    '宠物医院', '宠物医生', '兽医', '找兽医', '宠物诊所',
    '猫', '猫咪', '养猫', '猫粮', '猫砂', '猫生病',
    '狗', '狗狗', '养狗', '狗粮', '遛狗', '狗生病',
    '宠物美容', '宠物洗澡', '宠物造型', '剪毛', '梳毛',
    '寄养', '宠物寄养', '宠物托管', '宠物酒店', '出差寄养', '旅游寄养',
    '宠物用品', '宠物食品', '宠物零食', '宠物玩具',
    '打疫苗', '宠物疫苗', '绝育', '驱虫', '体检',
    '宠物训练', '训狗', '行为矫正',
    '领养', '宠物领养', '救助', '流浪猫', '流浪狗',
    'pet', 'pet store', 'pet shop', 'veterinary', 'vet', 'veterinarian',
    'grooming', 'pet grooming', 'dog walker', 'pet boarding', 'pet sitting',
    'cat', 'dog', 'puppy', 'kitten', 'pet adoption', 'pet hospital',
  ],
  'svc-dry-cleaning': [
    '干洗', '干洗店', '找干洗', '干洗推荐',
    '洗衣', '洗衣店', '洗衣服', '送洗',
    '熨烫', '熨衣服', '熨烫服务',
    '西装', '洗西装', '干洗西装', '礼服', '洗礼服',
    '羽绒服', '洗羽绒服', '大衣', '洗大衣', '皮草', '皮衣',
    '窗帘', '洗窗帘', '地毯', '洗地毯', '桌布',
    '改衣', '缝补', '修改', '拉链', '换拉链', '缩短', '加长',
    '去渍', '去污渍', '油渍', '红酒渍', '血渍',
    '取送', '上门取送', '快递洗衣',
    'dry cleaning', 'dry cleaner', 'laundry', 'laundromat',
    'ironing', 'pressing', 'suit cleaning', 'dress cleaning',
    'stain removal', 'wash and fold', 'alterations', 'pick up delivery',
  ],
  'svc-phone-repair': [
    '手机维修', '修手机', '找修手机', '手机维修推荐',
    '电脑维修', '修电脑', '找修电脑', '电脑维修推荐',
    '换屏', '换手机屏', '碎屏', '屏幕碎了', '屏幕维修',
    '换电池', '电池不行了', '续航差', '手机电池',
    'iPhone', '苹果手机', '安卓', '三星', '华为', '小米',
    'iPad', '平板', '平板维修',
    '进水', '手机进水', '手机掉水里',
    '充不进电', '充电口', '喇叭', '话筒', '听筒', '摄像头',
    '电脑', '笔记本', '台式机', 'Mac', 'MacBook', 'Windows',
    '慢', '电脑慢', '蓝屏', '死机', '中毒', '杀毒',
    '数据恢复', '照片恢复', '文件恢复', '硬盘', 'SSD',
    '升级', '加内存', '换硬盘',
    'phone repair', 'cell phone repair', 'screen repair', 'iPhone repair',
    'computer repair', 'laptop repair', 'Mac repair', 'PC repair',
    'screen replacement', 'battery replacement', 'data recovery',
  ],
  'svc-tailor': [
    '裁缝', '裁缝店', '找裁缝', '裁缝推荐',
    '改衣', '改衣服', '改裤子', '改裙子', '改西装',
    '定制', '定制西装', '定制旗袍', '定制礼服', '量身定制',
    '缝纫', '缝补', '修改', '修改衣服',
    '裤脚', '改裤脚', '缩短', '加长', '收腰', '放大', '改小',
    '拉链', '换拉链', '扣子', '换扣子', '修拉链',
    '婚纱', '改婚纱', '婚纱修改', '伴娘服',
    '西装', '改西装', '西装定制', '衬衫定制',
    '旗袍', '中式服装', '传统服装', '唐装',
    '窗帘', '做窗帘', '定制窗帘',
    'tailor', 'tailor shop', 'alteration', 'alterations', 'seamstress',
    'custom suit', 'dress alteration', 'hemming', 'fitting',
    'wedding dress alteration', 'sewing', 'custom clothing',
  ],
  'svc-wedding': [
    '婚庆', '婚庆公司', '找婚庆', '婚庆推荐',
    '婚礼', '婚礼策划', '婚礼布置', '婚礼现场', '婚礼流程',
    '结婚', '要结婚', '筹备婚礼',
    '婚纱', '婚纱礼服', '租婚纱', '买婚纱', '试婚纱',
    '司仪', '婚礼司仪', '主持人', 'MC', '中文司仪',
    '婚纱摄影', '婚纱照', '婚礼跟拍', '婚礼摄影', '婚礼摄像',
    '婚车', '花车', '租车',
    '婚礼花艺', '鲜花', '花束', '新娘捧花', '现场花艺',
    '婚宴', '酒席', '婚礼酒店', '婚礼餐厅', '婚宴预订',
    '婚礼蛋糕', '订蛋糕', '翻糖蛋糕',
    '婚礼化妆', '新娘化妆', '新娘造型', '伴娘造型',
    '乐队', 'DJ', '婚礼音乐', '现场乐队',
    '婚礼请帖', '请帖', '红包', '礼金',
    'wedding', 'wedding planner', 'wedding planning', 'bridal',
    'wedding venue', 'wedding photographer', 'wedding dress',
    'florist', 'wedding cake', 'DJ', 'officiant', 'wedding MC',
  ],
  'svc-funeral': [
    '殡葬', '殡葬服务', '殡仪馆', '找殡葬', '殡葬推荐',
    '丧葬', '丧事', '办丧事', '后事',
    '追悼', '追悼会', '告别仪式', '葬礼', '追思会',
    '火化', '火葬', '骨灰', '骨灰盒', '骨灰寄存',
    '土葬', '墓地', '墓园', '买墓地', '墓碑',
    '寿衣', '花圈', '挽联', '遗像',
    '中式葬礼', '佛教仪式', '道教仪式',
    '遗体运送', '遗体回国', '国际运送',
    '丧葬保险', '预先安排', '提前规划',
    'funeral', 'funeral home', 'funeral service', 'burial', 'cremation',
    'memorial', 'cemetery', 'casket', 'obituary', 'wake',
    'Chinese funeral', 'repatriation', 'pre-planning',
  ],
  'svc-storage': [
    '仓储', '仓库', '找仓库', '租仓库',
    '自存', '自存仓', '自存储', '迷你仓', '存东西',
    '存储', '存放', '临时存储', '长期存储',
    '搬家存储', '搬家临时存放', '搬家寄存',
    '大件', '存家具', '存行李', '存箱子',
    '气候控制', '恒温仓', '温度控制',
    '安全', '监控', '24小时', '随时取用',
    '多大', '尺寸', '价格', '月租', '按月',
    'storage', 'self storage', 'storage unit', 'mini storage',
    'moving storage', 'climate controlled', 'storage facility',
    'Public Storage', 'Extra Space', 'CubeSmart', 'rent storage',
  ],
  'svc-jewelry': [
    '珠宝', '珠宝店', '找珠宝', '珠宝推荐',
    '钟表', '手表', '修表', '换电池', '表带', '保养手表',
    '首饰', '项链', '手链', '手镯', '戒指', '耳环', '耳钉', '吊坠',
    '金饰', '黄金', '白金', '铂金', 'K金', '18K', '24K',
    '钻石', '钻戒', '婚戒', '订婚戒指', '结婚戒指',
    '玉', '翡翠', '和田玉', '玉镯', '玉佩',
    '珍珠', '珍珠项链', '天然珍珠',
    '定制', '定制首饰', '定制戒指', '刻字',
    '回收', '回收黄金', '卖金', '典当',
    '修理', '修首饰', '改戒指', '换链子', '重新镶嵌',
    '清洗', '首饰清洗', '抛光', '翻新',
    'jewelry', 'jewelry store', 'jeweler', 'watch', 'watch repair',
    'diamond', 'gold', 'ring', 'necklace', 'bracelet', 'earring',
    'engagement ring', 'wedding band', 'custom jewelry', 'jade',
  ],
  'svc-daycare-senior': [
    '老人', '老人家', '长辈', '父母', '养老',
    '老人护理', '护理', '照顾老人', '陪护', '看护',
    '老人院', '养老院', '敬老院', '护理院', '康复中心',
    '居家护理', '上门护理', '家庭护理', '保姆', '护工',
    '老人日托', '日间照料', '成人日托', '老人活动中心',
    '白卡护理', 'Medicaid护理', '长期护理', '保险',
    '阿尔茨海默', '老年痴呆', '失智', '记忆力', '认知障碍',
    '中风', '康复', '偏瘫', '行动不便', '轮椅',
    '送餐', '老人送餐', '上门送餐',
    '华人养老', '中文护理', '说中文的', '华人老人院',
    'senior care', 'elderly care', 'nursing home', 'assisted living',
    'home care', 'home health aide', 'adult day care', 'caregiver',
    'Medicaid', 'long term care', 'dementia', 'Alzheimer',
    'Chinese senior care', 'senior center',
  ],
  'svc-religious': [
    '教堂', '教会', '找教堂', '找教会', '附近教堂',
    '华人教会', '中文教会', '中文礼拜', '华人基督教',
    '礼拜', '做礼拜', '主日', '崇拜', '聚会', '团契',
    '牧师', '传道', '祷告', '读经', '查经', '圣经',
    '天主教', '基督教', '新教', '浸信会', '卫理公会', '长老会',
    '寺庙', '佛寺', '佛堂', '找寺庙', '拜佛', '烧香', '念经',
    '佛教', '道教', '道观',
    '伊斯兰', '清真寺', '穆斯林',
    '受洗', '洗礼', '婚礼', '葬礼', '弥撒',
    '主日学', '儿童主日学', '青年团契', '诗班', '唱诗班',
    'church', 'Chinese church', 'temple', 'Buddhist temple',
    'worship', 'Sunday service', 'Bible study', 'prayer',
    'Catholic', 'Christian', 'Protestant', 'Baptist', 'mosque',
  ],
  'svc-community-org': [
    '社区', '社区组织', '社区中心', '社区服务',
    '社团', '华人社团', '华人组织', '华人团体',
    '协会', '商会', '华人商会', '中华商会',
    '同乡会', '老乡会', '福建同乡会', '广东同乡会', '温州同乡会',
    '互助', '互助会', '互助组织', '志愿者', '义工',
    '活动', '社区活动', '华人活动', '公益活动',
    '中文学校', '周末学校', '文化活动', '春节', '中秋', '端午',
    '法律援助', '免费咨询', '免费翻译', '免费报税',
    '新移民', '移民服务', '新移民帮助', '融入',
    '红十字', '慈善', '捐款', '筹款',
    'community', 'community center', 'community organization', 'nonprofit',
    'association', 'Chinese association', 'chamber of commerce',
    'volunteer', 'charity', 'immigrant service', 'social service',
  ],
};

async function main() {
  console.log('🔤 Populating search_terms for categories\n');

  let updated = 0;
  for (const [slug, terms] of Object.entries(TERMS)) {
    await update(slug, terms);
    updated++;
  }

  console.log(`\n✅ Updated ${updated} categories`);
}

main().catch(console.error);
